export interface Product {
  id: string;
  name: string;
  category: 'interior' | 'exterior' | 'decor' | 'special';
  subCategory?: string;
  line: string;
  description: string;
  coverage: string; 
  coverageMultiplier: number; 
  dryingTime: string; 
  finishes: string[]; 
  tag: string;
  features: string[];
  image: string;
  fallbackImage: string;
  dilution: string;
  density: string;
  cov: string;
  outils: string;
  preparation: string;
  longDescription: string;
  usage: string[];
  pdfUrl?: string;
}

export interface Color {
  id: string;
  name: string;
  hex: string;
  category: 'chaleureux' | 'mineral' | 'nature' | 'neutre';
  description: string;
}

export interface Room {
  id: string;
  name: string;
  label: string;
  viewBox: string;
  elements: { id: string; name: string; defaultColor: string; d: string }[];
}

export const PRODUCTS_DB: Product[] = [
  // ==================== INTÉRIEUR - DÉCO ====================
  {
    id: "int-chromia",
    name: "CHROMIA",
    pdfUrl: "/prismacolorwebsite/fiches/chromia.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Effet nacré",
    description: "Peinture décorative haut de gamme à effet velours mat soyeux qui magnifie l'éclairage intérieur.",
    coverage: "4 m²/Kg par couche",
    coverageMultiplier: 4, // La valeur utilisée par la formule (m²/kg)
    features: ["Bon pouvoir couvrant. ", "Très facile à appliquer"],
    dryingTime: "Hors poussières: 1H, Recouvrable : 4H",
    finishes: ["Marbré", "satiné"],
    image: "/prismacolorwebsite/images/Chromia.png",
    fallbackImage: "/src/assets/images/Chromia.png",
    dilution: "5 à 10 % avec d'eau à 25 °C",
    density: "1.6 ± 0.05 kg/l",
    cov: "Faible Cov ",
    outils: " Taloche inox ou couteau à enduire.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "CHROMIA est une peinture décorative écologique, offrant un aspect unique grâce à sa capacité à refléter la lumière sous tous les angles, apportant ainsi une touche élégante et lumineuse. Idéale pour créer une ambiance douce et raffinée.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-cira-mineralia",
    name: "CIRA MINERALIA",
    pdfUrl: "/prismacolorwebsite/fiches/CiraMineralia.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Tadelakt",
    description: " vernis acrylique en phase aqueuse, d'aspect nacré et mat, conçu pour la protection et la décoration des produits décoratifs",
    coverage: "12 à 14 m²/Kg selon la porosité du support.",
    coverageMultiplier: 13,
    dryingTime: "Sec : 2h, Hors poussière : 1H",
    finishes: ["Mat", "Nacré"],
    features: ["Sans odeur", "Très facile à appliquer.", "Disponible  en mate et nacré"],
    image: "/prismacolorwebsite/images/CiraMineralia.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "  110 ± 5 KU à 25°C. ",
    cov: "Faible Cov",
    outils: "Éponge",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "ve1 ± rnis acrylique en phase aqueuse, d'aspect nacré et mat, conçu pour la protection et la décoration des produits décoratifs : Minéralia. ",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-fluorina",
    name: "FLUORINA",
    pdfUrl: "/prismacolorwebsite/fiches/Fluorina.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Sablé Nacré",
    description: "peinture décorative écologique de prestige en phase aqueuse à effet sablé nacré, conçue spécialement pour la haute décoration des espaces intérieurs. ",
    coverage: "5-6 m²/Kg par couche",
    coverageMultiplier: 5.5,
    dryingTime: "Sec  : 3H, Hors Poussière : 1h",
    finishes: ["Sablé Nacré"],
    features: ["Bon pouvoir couvrant", "Peinture lessivable"],
    image: "/prismacolorwebsite/images/Fluorina.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% à 10% max.",
    density: "650 ± 50 POISE à 25°C",
    cov: "Faible cov",
    outils: "Brosse, Spalter",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "FLUORINA est un revêtement décoratif écologique pour intérieurs composé de charges métalliques et d'agrégats de quartz sélectionnés qui produisent des effets visuels haut de gamme et créent un jeu unique de lumière et d'ombres.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-vega-star",
    name: "VEGA STAR",
    pdfUrl: "/prismacolorwebsite/fiches/VegaStar.pdf",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Nacré",
    description: "peinture décorative Ecologique, conçue spécialement pour la haute  décoration  des espaces en intérieur, donnant un effet nacré,  étincelant et luminescent grâce à sa pigmentation métallisée ultra fine.",
    coverage: " 4 m²/Kg par couche",
    coverageMultiplier: 4 ,
    dryingTime: "Recouvrable : 4h, Hors Poussière : 1h",
    finishes: ["Nacré", "métalisé"],
    features: ["Bon pouvoir couvrant ", "Peinture lessivable"],
    image: "/prismacolorwebsite/images/VegaStar.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% à 10% max.",
    density: "800 ± 100 poises à 25°C",
    cov: "Faible cov",
    outils: "pistolet rouleau, Taloche plastique,Spatule",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Découvrez l'élégance intemporelle de la peinture décorative haut de gamme VEGA STAR. Conçue pour sublimer vos intérieurs, VEGA STAR allie une qualité exceptionnelle, une palette de couleurs raffinée et des finitions soignées. Chaque teinte est méticuleusement sélectionnée pour créer des ambiances uniques et durables.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-beton-a-cire",
    name: "BÉTON À CIRÉ",
    pdfUrl: "/prismacolorwebsite/fiches/BetonACire.pdf",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Effet Ciment",
    description: " un mortier monocomposant en poudre à base de ciment, de granulats de marbre et de silice, de résines synthétiques et d'additifs spéciaux",
    coverage: " 2-4 m²/Kg par couche",
    coverageMultiplier: 3,
    dryingTime: "Hors Poussière : 1H, Recouvrable : 12H",
    finishes: ["Lisse" , "Minéral"],
    features: ["Rendement élevé", "Très facile à appliquer", "Très bonne adhérence"],
    image: "/prismacolorwebsite/images/Vide.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 20% à 25% max.",
    density: "-",
    cov: "Faible cov",
    outils: "lisseuse en inox , platoir inox",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "un mortier monocomposant en poudre à base de ciment, de granulats de marbre et de silice, de résines synthétiques et d'additifs spéciaux qui réduisent l'absorption et la perméabilité de l'eau et lui confèrent une maniabilité et une docilité optimales pour son application, ainsi que des propriétés mécaniques, d'abrasion, d'adhérence et de résistance élevées.  ",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-onyx",
    name: "ONYX",
    pdfUrl: "/prismacolorwebsite/fiches/Onyx.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Marbré",
    description: "Peinture décorative Ecologique, pour intérieur à aspect marbré et brillant",
    coverage: "4 m²/Kg par couche",
    coverageMultiplier: 4,
    dryingTime: "Hors Poussière: 1H, Recouvrable : 4H",
    finishes: ["Satiné", "Marbré"],
    features: ["Bon pouvoir couvrant", "Blancheur très élevée", "Très facile à appliquer"],
    image: "/prismacolorwebsite/images/Onyx.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% à 10% max.",
    density: "1400 ± 200 POISE à 25°C",
    cov: "Faible cov",
    outils: "Taloche inox, couteau à enduire",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "ONYX est une Peinture décorative en phase aqueuse qui a un aspect marbré et brillant à l'ancienne. Convient à tous les espaces intérieurs.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-prisma-cire",
    name: "PRISMA CIRE",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaCire.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Cire de Protection ",
    description: "cire à base d’eau particulièrement recommandée pour la protection et l'amélioration de la brillance des stucs comme ONYX",
    coverage: "10-12 m²/Kg par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec : 24h",
    finishes: ["Brillant"],
    features: ["Très Bonne propriété hydrofuge", "Rendement élevé", "Très facile à appliquer", "Très bonne adhérence"],
    image: "/prismacolorwebsite/images/Vide.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% à 10% max.",
    density: "1 ± 0.05 Kg/L à 25°C",
    cov: "Faible cov",
    outils: "Éponge",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "une cire à base d’eau particulièrement recommandée pour la protection et l'amélioration de la brillance des stucs comme ONYX.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-iridium",
    name: "IRIDIUM",
    pdfUrl: "/prismacolorwebsite/fiches/Iridium.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Nacré , métallisé",
    description: "une peinture décorative écologique de prestige en phase aqueuse, conçue spécialement pour la haute décoration des espaces intérieurs. Ses ramages décoratifs ainsi que son aspect moiré nacré.",
    coverage: "4-5 m²/Kg par couche",
    coverageMultiplier: 4.5,
    dryingTime: "Hors Poussière: 1H, Recouvrable : 4H",
    finishes: ["Nacré", "métalisé"],
    features: ["Bon pouvoir couvrant ", "Peinture lessivable"],
    image: "/prismacolorwebsite/images/Iridium.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% à 10% max.",
    density: "140 ± 5 KU à 25°C",
    cov: "Faible cov",
    outils: "Spatule, Taloche plastique",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "IRIDIUM est une peinture décorative écologique, caractérisée par un effet nacré subtil et un toucher soyeux. Elle allie esthétisme et performance pour embellir les espaces intérieurs. Facile à appliquer, elle apporte une touche élégante et moderne.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-mineralia",
    name: "MINERALIA",
    pdfUrl: "/prismacolorwebsite/fiches/Mineralia.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Tadelakt",
    description: "une peinture décorative minérale à base de chaux pour intérieurs, à appliquer sur différents supports ; Enduits en plâtre et matériaux dérivés du plâtre à épiderme cartonné, enduits au mortier de liants hydrauliques, parements de béton.",
    coverage: "2-3 m²/Kg par couche",
    coverageMultiplier: 2.5,
    dryingTime: "Hors Poussière :1h, Recouvrable : 4h",
    finishes: ["Nacré",  "mate"],
    features: [" Aspect mat où nacré selon l'effet réalisé", "Pouvoir couvrant et garnissant élevé"],
    image: "/prismacolorwebsite/images/Mineralia.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% à 10% max.",
    density: "1.65 ± 0.05 Kg/L à 25°C",
    cov: "Faible cov",
    outils: "Platoir inox",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "MINERALIA est une peinture décorative écologique inspirée du Tadelakt, un revêtement traditionnel marocain à base de chaux et de pigments naturels. Elle confère brillance et douceur aux surfaces, et est particulièrement prisée dans les hammams, les salons. MINERALIA se termine par une couche de vernis ou de Prisma cire pour améliorer sa résistance et sa durabilité.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-prisma-teinte",
    name: "PRISMA TEINTE",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaTeinte.pdf",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Colorant Universel",
    description: "Système de colorants universels à haute concentration pour teinter et personnaliser avec précision toutes les bases acryliques.",
    coverage: "-",
    coverageMultiplier: 1,
    dryingTime: "-",
    finishes: ["-"],
    features: ["Pigments minéraux inaltérables", "Compatibilité totale assurée", "Stabilité absolue de la couleur", "Formule super-concentrée"],
    image: "/src/assets/images/regenerated_image_1780776524454.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "-",
    cov: "Faible cov",
    outils: "-",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Système de colorants universels à haute concentration pour teinter et personnaliser avec précision toutes les bases acryliques. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-prisma-lux",
    name: "PRISMA LUX",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaLux.pdf",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Laque Brillante Prestige",
    description: " concentré métallisé décoratif en phase aqueuse, pour métal, plâtre, bois et béton.",
    coverage: "10-12 m²/Kg par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec  : 2h, Hors Pousière : 30 min ",
    finishes: ["Nacré", "Doré", "Argenté" , "Bronze"],
    features: ["Très facile à appliquer", "Très faible odeur."],
    image: "/src/assets/images/regenerated_image_1780776524863.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. ",
    density: "1,12 ± 0.05 Kg/L",
    cov: "Faible cov",
    outils: "Pinceau, Pistolet et Rouleau.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: " un concentré métallisé décoratif en phase aqueuse, pour métal, plâtre, bois et béton. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },

  // ==================== INTÉRIEUR - IMPRESSION ====================
  {
    id: "int-prisma-prim-extra",
    name: "PRISMA PRIM EXTRA",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaPrim.pdf",
    category: "interior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression",
    tag: "Satiné",
    description: "une impression universelle écologique transparente en phase aqueuse, conçue pour l'imperméabilisation et la protection des supports de  maçonnerie, de bois et de plâtre peut être aussi utilisée",
    coverage: "10-12 m²/Kg par couche",
    coverageMultiplier: 11,
    dryingTime: "Hors Poussière : 1h, Sec : 1H  30 min",
    finishes: ["Satiné"],
    features: ["Très Bonne propriété hydrofuge", "Rendement élevé", "Très facile à appliquer", "Très bonne adhérence"],
    image: "/prismacolorwebsite/images/PrismaPrimExtra.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: " 5% à 10 % avec de l'eau à 25 °C. ",
    density: "1 ± 0.05 Kg/L",
    cov: "Faible cov",
    outils: "Rouleau ou brosse",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "une impression universelle écologique transparente en phase aqueuse, conçue pour l'imperméabilisation et la protection des supports de  maçonnerie, de bois et de plâtre peut être aussi utilisée",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },
  {
    id: "int-prisma-blanc-fix",
    name: "PRISMA BLANC FIX",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaBlancFix.pdf",
    category: "interior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression",
    tag: "Accrochage et Blocage de Pores",
    description: "une impression écologique pigmentée en phase aqueuse, conçue pour le blocage des pores et l'accrochage des finitions sur le support.",
    coverage: "10-12 m²/Kg par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec  : 1h, Recouvrable : 3h , Hors Poussière : 30 min",
    finishes: ["Satiné"],
    features: ["Très facile à appliquer", "Très bonne adhérence", "Rendement élevé"],
    image: "/prismacolorwebsite/images/BlancFixe.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1 ± 0.05 Kg/L",
    cov: "Faible cov",
    outils: "Rouleau ou brosse",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "une impression écologique pigmentée en phase aqueuse, conçue pour le blocage des pores et l'accrochage des finitions sur le support.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },
  {
    id: "int-prisma-fondo",
    name: "PRISMA FONDO",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaFondo.pdf",
    category: "interior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression",
    tag: "Primaire Texturé",
    description: "Sous-couche d'accroche grainée ou micro-sablée, indispensable pour la dépose mécanique des enduits à effets décoratifs.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Crée une accroche rugueuse", "Facilite l'application sur plâtre", "Empêche le glissement d'enduit", "Haute teneur en charges solides"],
    image: "/prismacolorwebsite/images/PrismaFondo.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Sous-couche d'accroche grainée ou micro-sablée, indispensable pour la dépose mécanique des enduits à effets décoratifs. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },

  // ==================== INTÉRIEUR - ENDUIT ====================
  {
    id: "int-prisma-pate",
    name: "PRISMA PATE",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaPate.pdf",
    category: "interior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits",
    tag: "Enduit ",
    description: "un enduit vinylique en pâte, prêt à l'emploi, conçu pour égaliser les supports en ciment ou plâtre et rattraper les irrégularités de surface.",
    coverage: "2-4 m²/kg ",
    coverageMultiplier: 3,
    dryingTime: "Hors poussière : 1h, Recouvrable : 6h",
    finishes: ["Mate"],
    features: ["Très facile à appliquer", "Grand pouvoir garnissant", "Très bonne adhérence", "Pas de frisage" , "Facile à poncer"],
    image: "/prismacolorwebsite/images/PrismaPate.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "5% à 10% avec de l'eau à 25 °C.",
    density: "1.80 ± 0.05 g/cm³",
    cov: "Faible cov",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "un enduit vinylique en pâte, prêt à l'emploi, conçu pour égaliser les supports en ciment ou plâtre et rattraper les irrégularités de surface.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },
  {
    id: "int-prisma-pret",
    name: "PRISMA PRET",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaPret.pdf",
    category: "interior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits",
    tag: "Lissage  des supports",
    description: "un enduit en poudre d'intérieur très  garnissant  recommandé pour le lissage  des supports en ciments.",
    coverage: "pour enduisage 1 à 2  m²/kg, et pour ratissage 2 à 3 m²/kg",
    coverageMultiplier: 2,
    dryingTime: "Hors poussières : 1 H, Recouvrable : 12 H",
    finishes: ["Poudre"],
    features: ["Très facile à appliquer", "Grand pouvoir garnissant.", "Très bonne adhérence.", "Pas de frisage.", "Facile à poncer."],
    image: "/prismacolorwebsite/images/PrismaPret.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "20% à 25% avec de l'eau à 25 °C.",
    density: "-",
    cov: "Faible cov",
    outils: "Couteau à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "un enduit en poudre d'intérieur très  garnissant  recommandé pour le lissage  des supports en ciments.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },
  {
    id: "int-prisma-stop",
    name: "PRISMA STOP",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaStop.pdf",
    category: "interior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits",
    tag: "Lissage",
    description: "un enduit en pâte conçu pour les travaux soignés en intérieur. Il rebouche et masque les aspérités de surface, donne lieu à une surface lisse permettant l'obtention des finitions",
    coverage: "2-3kg/m² selon support",
    coverageMultiplier: 2.5,
    dryingTime: "Hors poussière : 1h, Recouvrable : 6h",
    finishes: ["Mate"],
    features: ["Très facile à appliquer", "Pas de frisage", "Bon garnissant", "Très bonne adhérence"],
    image: "/src/assets/images/regenerated_image_1780776529269.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Prêt à l'emploi ",
    density: "1.90 ± 0.05 g/cm³",
    cov: "Faible cov",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "un enduit en pâte conçu pour les travaux soignés en intérieur. Il rebouche et masque les aspérités de surface, donne lieu à une surface lisse permettant l'obtention des finitions",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },

  // ==================== INTÉRIEUR - VERNIS ====================
  {
    id: "int-prisma-pores",
    name: "PRISMA PORES",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaPores.pdf",
    category: "interior",
    subCategory: "VERNIS",
    line: "Gamme Vernis",
    tag: "surfaceur pour le bois",
    description: "un surfaceur pour le bois, il remplit les pores et donne après égrenage une surface lisse qui facilite l'application de la finition.",
    coverage: "12-14 m²/L par couche",
    coverageMultiplier: 13,
    dryingTime: "Hors poussière : 30min , Sec : 4h",
    finishes: ["Satiné "],
    features: [   "Très facile à appliquer.", "Rendement élevé."],
    image: "/prismacolorwebsite/images/PrismaPores.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "5 à 30% avec de l'eau à 25 °C.",
    density: "1.03 ± 0.05 Kg/L",
    cov: "Faible cov",
    outils: "Pinceau ou pistolet ",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "un surfaceur pour le bois, il remplit les pores et donne après égrenage une surface lisse qui facilite l'application de la finition.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
    id: "int-prisma-wood",
    name: "PRISMA WOOD",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaWood.pdf",
    category: "interior",
    subCategory: "VERNIS",
    line: "Gamme Vernis",
    tag: "Polyuréthane Ultra-Dureté",
    description: "Vernis polyuréthane monocomposant brillant formulé pour la vitrification des parquets, escaliers et tables d'art.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Résistance totale aux rayures", "Fini de haut poli mirifique", "Imperméabilité absolue aux liquides", "Anti-jaunissement renforcé"],
    image: "/src/assets/images/regenerated_image_1780776530905.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Vernis polyuréthane monocomposant brillant formulé pour la vitrification des parquets, escaliers et tables d'art. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },

  // ==================== INTÉRIEUR - HYGIÈNE ====================
  {
    id: "int-peinture-antibacterienne",
    name: "PEINTURE ANTIBACTÉRIENNE",
    pdfUrl: "/prismacolorwebsite/fiches/PeintureAntibacterienne.pdf",
    category: "interior",
    subCategory: "HYGIÈNE",
    line: "Gamme Hygiène",
    tag: "Ions d'Argent Actifs",
    description: "Peinture acrylique mate désinfectante, enrichie en ions d'argent détruisant les virus et bactéries au contact.",
    coverage: "10-11 m²/L par couche",
    coverageMultiplier: 10.5,
    dryingTime: "Sec : 1.5h, Recouvrable : 6h",
    finishes: ["Velouté", "Satiné Hygiénique"],
    features: ["Protection active permanente 24h", "Résiste aux lavages désinfectants", "Certifié contact alimentaire", "Idéal pour crèches et hôpitaux"],
    image: "/src/assets/images/regenerated_image_1780776530600.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Eau claire : 5% à 10% maximum.",
    density: "1.45 ± 0.05 g/cm³",
    cov: "< 8 g/L (Certifié anti-microbien)",
    outils: "Rouleau microfibre, brosse à rechampir.",
    preparation: "Laver et désinfecter le support si présence antérieure de moisissures.",
    longDescription: "Peinture acrylique mate désinfectante, enrichie en ions d'argent détruisant les virus et bactéries au contact. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Milieux hospitaliers", "Chambres d'enfants", "Cuisines et crèches"]
  },

  // ==================== INTÉRIEUR - ACRYLIQUE ====================
  {
   id: "int-prisma-plast",
    name: "PRISMA PLAST",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaPlast.pdf",
    category: "interior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques",
    tag: "Acrylique",
    description: "une peinture acrylique, mate en phase aqueuse destinée pour les travaux d'intérieures et extérieures.",
    coverage: "4-5 m²/kg",
    coverageMultiplier: 4.5,
    dryingTime: "Hors poussières : 15 min, Sec : 30 min, Recouvrable : 3h",
    finishes: ["mate lisse"],
    features: ["Bon pouvoir couvrant", "Rendement élevé"],
    image: "/prismacolorwebsite/images/PrismaPlast.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "5 à 10 % avec d'eau à 25 °C",
    density: "1.78 ± 0.05 Kg/L",
    cov: "Faible Cov",
    outils: "un rouleau, pinceau ou pistolet.",
    preparation: "Pour tous les travaux, les supports doivent être sains, secs.",
    longDescription: "une peinture acrylique, mate en phase aqueuse destinée pour les travaux d'intérieures et extérieures.",
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },
  {
    id: "int-prisma-vinyl",
    name: "PRISMA VINYL",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaVinyl.pdf",
    category: "interior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques",
    tag: "Finition Souple de Tradition",
    description: "Peinture traditionnelle à base de copolymères vinyliques offrant un excellent rapport pouvoir couvrant / prix.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 2h, Recouvrable : 6h",
    finishes: ["Satiné", "Mat velouté"],
    features: ["Blancheur mate respirante", "Idéal sur plaques de plâtre", "Bonne opacité en deux passes", "Application fluide sans traînées"],
    image: "/prismacolorwebsite/images/PrismaVinyl.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Eau claire : 10% max.",
    density: "1.41 ± 0.05 g/cm³",
    cov: "< 12 g/L (Haute lessivabilité)",
    outils: "Rouleau polyester 12mm, brosse, Airless.",
    preparation: "Appliquer une sous-couche compatible pour homogénéiser l'absorption.",
    longDescription: "Peinture traditionnelle à base de copolymères vinyliques offrant un excellent rapport pouvoir couvrant / prix. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },
  {
   id: "int-ecologia",
    name: "ECOLOGIA",
    pdfUrl: "/prismacolorwebsite/fiches/Ecologia.pdf",
    category: "interior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques",
    tag: "Zéro COV Certifié",
    description: "est une peinture acrylique, en phase aqueuse présentant un aspect mat lisse, ayant à une très faible odeur à l'application.", // [cite: 662]
    coverage: "8-10 m²/kg", // [cite: 671]
    coverageMultiplier: 9,
    dryingTime: "Hors poussières : 15 MIN, Sec : 1 H, Recouvrable : 3 H", // [cite: 686, 687, 688]
    finishes: ["mate lisse"], // [cite: 669]
    features: ["Bon pouvoir couvrant", "Peinture lessivable"], // [cite: 665, 666]
    image: "/prismacolorwebsite/images/Ecologia.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "5 à 10 % avec d'eau à 25 °C", // [cite: 675]
    density: "1.43 ± 0.05 kg/l", // [cite: 672]
    cov: "Faible Cov",
    outils: "un rouleau, pinceau ou pistolet.", // [cite: 674]
    preparation: "Pour tous les travaux, les supports doivent être sains, secs.", // [cite: 678]
    longDescription: "est une peinture acrylique, en phase aqueuse présentant un aspect mat lisse, ayant à une très faible odeur à l'application.", // [cite: 662]
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },

  // ==================== INTÉRIEUR - SOLUTIONS ====================
  {
    id: "int-enduit-carrelage",
    name: "ENDUIT CARRELAGE",
    pdfUrl: "/prismacolorwebsite/fiches/EnduitCarrelage.pdf",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Rénovation Directe Faïence",
    description: "Enduit d'égalisation et d'accroche étanche conçu pour masquer directement les joints de carrelage intérieurs.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Adhérence totale sur verre et céramique", "Évite d'enlever l'ancien carrelage", "Préparation résiliente", "Garantit des murs intérieurs plats"],
    image: "/prismacolorwebsite/images/EnduitCarrelage.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Enduit d'égalisation et d'accroche étanche conçu pour masquer directement les joints de carrelage intérieurs. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-antifissure",
    name: "ANTIFISSURE",
    pdfUrl: "/prismacolorwebsite/fiches/AntiFissure.pdf",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Élastique Anti-Fissures",
    description: "Traitement acrylique souple de rebouchage pour réparations de fissures actives intérieures sujettes aux micro-mouvements.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Allongement exceptionnel", "Suit les mouvements de dilatation", "Recouvrable par toutes finitions", "Excellente tenue dans le temps"],
    image: "/prismacolorwebsite/images/AntiFissure.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Traitement acrylique souple de rebouchage pour réparations de fissures actives intérieures sujettes aux micro-mouvements. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-antihumidite",
    name: "ANTIHUMIDITÉ",
    pdfUrl: "/prismacolorwebsite/fiches/Antihumidité.pdf",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Bloqueur d'Infiltration",
    description: "Peinture solvantée d'étanchéité intérieure bloquant activement l'humidité dans les caves, sous-sols et buanderies.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Directement applicable sur fond humide", "Permet l'évaporation saine de l'eau", "Bloque l'humidité de capillarité", "Traitement curatif absolu"],
    image: "/prismacolorwebsite/images/Antihumidité.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Peinture solvantée d'étanchéité intérieure bloquant activement l'humidité dans les caves, sous-sols et buanderies. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-fongex",
    name: "FONGEX",
    pdfUrl: "/prismacolorwebsite/fiches/Fongex.pdf",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Assainissant Anti-Moisissure",
    description: "Solution liquide curative à large spectre pour éliminer et désinfecter les moisissures et lichens des zones obscures humides.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Action destructrice rapide", "Empêche la réapparition des mousses", "Pénètre profondément le support", "Facile d'application par brosse"],
    image: "/prismacolorwebsite/images/Fongex.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Solution liquide curative à large spectre pour éliminer et désinfecter les moisissures et lichens des zones obscures humides. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-prima-fix",
    name: "PRIMA FIX",
    pdfUrl: "/prismacolorwebsite/fiches/PrimaFix.pdf",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Fixateur Fort Solvanté",
    description: "Fixateur de fond incolore en solvant, conçu pour agglomérer durcir et fixer les plâtres farineux ou friables.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Pénétration sub-porale intense", "Consolide les bétons poreux", "Améliore le rendement des finitions", "Haute tenue aux alcalis"],
    image: "/src/assets/images/paint_bucket_int-prima-fix.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Fixateur de fond incolore en solvant, conçu pour agglomérer durcir et fixer les plâtres farineux ou friables. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-epoxy",
    name: "EPOXY",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaEpoxy.pdf",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Résine Sol Bi-Composante",
    description: "Système époxy fluide auto-lissant bi-composant haute performance pour sols intérieurs d'habitations d'ateliers.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Dureté vitreuse ultra-solide", "Résistance chimique aux hydrocarbures", "Aspect brillant impeccable", "Zéro jaunissement sous verre"],
    image: "/src/assets/images/regenerated_image_1780776539099.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Système époxy fluide auto-lissant bi-composant haute performance pour sols intérieurs d'habitations d'ateliers. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },

  // ==================== EXTÉRIEUR - DÉCO ====================
  {
    id: "ext-effet-beton",
    name: "EFFET BETON",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaEffetBeton.pdf",
    category: "exterior",
    subCategory: "DÉCO",
    line: "Gamme Déco Facade",
    tag: "Brut / Contemporain",
    description: "Enduit acrylique garnissant extérieur reproduisant parfaitement l'effet authentique du béton brut de décoffrage.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Mat structuré", "Aspect Béton"],
    features: ["Rendu architectural contemporain", "Masque les spectres de briques", "Protection anti-UV renforcée", "Haute perspirance à la vapeur"],
    image: "/src/assets/images/regenerated_image_1780776538686.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Enduit acrylique garnissant extérieur reproduisant parfaitement l'effet authentique du béton brut de décoffrage. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "ext-monocouche",
    name: "MONOCOUCHE",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaMonocouche.pdf",
    category: "exterior",
    subCategory: "DÉCO",
    line: "Gamme Déco Facade",
    tag: "Crépi Minéral Moderne",
    description: "Revêtement d'imperméabilisation monocouche à base de chaux et charges de quartz pour la mise en valeur des villas.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Mat structuré", "Aspect Béton"],
    features: ["Décoration en une seule passe", "Imperméabilisation certifiée", "Résistance au grattage", "Disponible en teintes chaudes du Maroc"],
    image: "/src/assets/images/regenerated_image_1780776539917.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Revêtement d'imperméabilisation monocouche à base de chaux et charges de quartz pour la mise en valeur des villas. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
   id: "ext-prisma-rex",
    name: "PRISMA REX",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaRex.pdf",
    category: "exterior",
    subCategory: "DÉCO",
    line: "Gamme Déco Facade",
    tag: "Revêtement Plastique Épais",
    description: "PRISMA REX est un revêtement de façade décoratif et garnissant, d'aspect taloché à base de grains de quartz", // [cite: 628]
    coverage: "1 à 2 kg/m²", // [cite: 649]
    coverageMultiplier: 0.75,
    dryingTime: "Hors poussière: 24heures, Dur: 48heure", // [cite: 638, 639]
    finishes: ["Granulé", "Granulométrie: 0,5 mm à 1.5 mm"], // [cite: 633, 635]
    features: ["Très facile à appliquer", "Masque les irrégularités du support"], // [cite: 642]
    image: "/src/assets/images/regenerated_image_1780776539392.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "dilué de 1% à 2% d'eau", // [cite: 647]
    density: "1,8 ± 0.05", // [cite: 630]
    cov: "Faible Cov",
    outils: "rouleau alvéolé pour aspect décoratif spatulé", // [cite: 647]
    preparation: "Pour tous les travaux, les supports doivent être sains et secs. Appliquer une couche de FIX MAR à l'aide d'un rouleau", // [cite: 645, 646]
    longDescription: "PRISMA REX est un revêtement de façade décoratif et garnissant, d'aspect taloché à base de grains de quartz", // [cite: 628]
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },

  // ==================== EXTÉRIEUR - IMPRESSION ====================
  {
     id: "ext-prisma-prim-extra",
    name: "PRISMA PRIM EXTRA",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaPrim.pdf",
    category: "exterior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression Facade",
    tag: "Primaire Hydrofuge",
    description: "Sous-couche acrylique hydrofuge extérieure d'accrochage à fort pouvoir régulateur de porosité maçonnerie.",
    coverage: "10-12 m²/L", 
    coverageMultiplier: 11,
    dryingTime: "Hors poussières : 1 H, Sec : 1 H 30 min", 
    finishes: ["Satiné"], 
    features: ["Très Bonne propriété hydrofuge", "Rendement élevé", "Très facile à appliquer", "Très bonne adhérence"], 
    image: "/prismacolorwebsite/images/PrismaPrimExtra.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "5 à 10 % avec d'eau à 25 °C", 
    density: "1 ± 0.05 Kg/L", 
    cov: "Faible Cov",
    outils: "Rouleau ou brosse", 
    preparation: "Appliquer en une seule couche mince. Eviter toute coulure ou surépaisseur", 
    longDescription: "Sous-couche acrylique hydrofuge extérieure d'accrochage à fort pouvoir régulateur de porosité maçonnerie.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },
  {
    id: "ext-blanc-fixe",
    name: "BLANC FIXE",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaBlancFix.pdf",
    category: "exterior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression Facade",
    tag: "Régulation Blancheur",
    description: "Primaire et bloqueur d'alcalis à fort extrait sec blanc, excellent pour stabiliser les façades extérieures sales ou anciennes.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Neutralise la laitance du béton", "Opacité immense sur fonds foncés", "Excellente tenue aux sels marins", "Améliore la durabilité extérieure"],
    image: "/prismacolorwebsite/images/BlancFixe.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Primaire et bloqueur d'alcalis à fort extrait sec blanc, excellent pour stabiliser les façades extérieures sales ou anciennes. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },
  {
    id: "ext-prima-fixe",
    name: "PRIMA FIXE",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaPrimaFixe.pdf",
    category: "exterior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression Facade",
    tag: "Fixateur de Maçonnerie",
    description: "Impression durcissante solvantée à forte capacité d'accrochage pour resserrer et agréger les enduits farineux.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Excellente pénétration micrométrique", "Bloque l'efflorescence alcaline", "Idéal avant les peintures de façade", "Applicable en conditions humides"],
    image: "/src/assets/images/regenerated_image_1780776541760.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Impression durcissante solvantée à forte capacité d'accrochage pour resserrer et agréger les enduits farineux. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },

  // ==================== EXTÉRIEUR - ENDUIT ====================
  {
    id: "ext-enduit-facade-lisse",
    name: "ENDUIT FACADE LISSE",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaEnduitFacade.pdf",
    category: "exterior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits Facade",
    tag: "Lissage Plat Parfait",
    description: "Enduit d'égalisation et de ratissage extérieur formulé pour niveler parfaitement les façades rugueuses.",
    coverage: "0.8 - 1.5 kg/m² selon support",
    coverageMultiplier: 1.2,
    dryingTime: "Sec complet : 12h, Recouvrable : 24h",
    finishes: ["Mat très fin"],
    features: ["Résistance totale aux intempéries", "Ponçage très simple", "Nivellement précis au mortier", "Excellente souplesse d'application"],
    image: "/prismacolorwebsite/images/EnduitFacadeLisse.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Prêt à l'emploi en pâte onctueuse.",
    density: "1.75 ± 0.05 g/cm³",
    cov: "< 2 g/L (Zéro COV)",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "Enduit d'égalisation et de ratissage extérieur formulé pour niveler parfaitement les façades rugueuses. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },
  {
    id: "ext-enduit-facade-130",
    name: "ENDUIT FACADE 130",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaEnduitFacade.pdf",
    category: "exterior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits Facade",
    tag: "Garnissant Mortier Lourd",
    description: "Enduit cimenteux de ragréage extérieur à fort pouvoir garnissant permettant de reboucher jusqu'à 5mm par couche.",
    coverage: "0.8 - 1.5 kg/m² selon support",
    coverageMultiplier: 1.2,
    dryingTime: "Sec complet : 12h, Recouvrable : 24h",
    finishes: ["Mat très fin"],
    features: ["Adhérence extraordinaire sur béton brut", "Aucun affaissement de matière", "Retrait réduit contrôlé", "Haut rendement de rattrapage"],
    image: "/prismacolorwebsite/images/EnduitFacade130.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Prêt à l'emploi en pâte onctueuse.",
    density: "1.75 ± 0.05 g/cm³",
    cov: "< 2 g/L (Zéro COV)",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "Enduit cimenteux de ragréage extérieur à fort pouvoir garnissant permettant de reboucher jusqu'à 5mm par couche. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },

  // ==================== EXTÉRIEUR - ACRYLIQUE ====================
  {
    id: "ext-prisma-protect",
    name: "PRISMA PROTECT",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaProtect.pdf",
    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Barrière Hydrofuge Invisible",
    description: "Traitement de protection extérieure totalement invisible et perlant protégeant des graisses et graffiti.",
    coverage: "10 m²/L",
    coverageMultiplier: 10,
    dryingTime: "Hors poussière : 1h, Sec : 2h",
    finishes: ["satiné"],
    features: ["Rendement élevé", "Très facile à appliquer", "Très Bonne propriété hydrofuge"],
    image: "/src/assets/images/paint_bucket_ext-prisma-protect.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Prêt à l'emploi",
    density: "1.1 ± 0.05 Kg/L",
    cov: "Faible Cov",
    outils: "Rouleau ou brosse.",
    preparation: "On applique à l'aide d'un Rouleau ou brosse PRISMA PROTECT tout en répartissant le produit de façon homogène sur le Support. Eviter toute coulure ou surépaisseur (Effet Béton).",
    longDescription: "Traitement de protection extérieure totalement invisible et perlant protégeant des graisses et graffiti.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
   id: "ext-prisma-vinyl",
    name: "PRISMA VINYL",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaVinyl.pdf",
    category: "exterior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques Facade",
    tag: "Finition Résistante Éco",
    description: "Revêtement acrylique fluide d'usage universel extérieur, parfait pour la coloration économique des maçonneries.",
    coverage: "6-7 m²/kg", // [cite: 508]
    coverageMultiplier: 6.5,
    dryingTime: "Hors poussières : 15 MIN, Sec : 30 MIN, Recouvrable : 3 H", // [cite: 523, 524, 525]
    finishes: ["mate lisse"], // [cite: 506]
    features: ["Bon pouvoir couvrant", "Peinture lessivable"], // [cite: 502, 503]
    image: "/prismacolorwebsite/images/PrismaVinyl.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "5 à 10 % avec d'eau à 25 °C", // [cite: 512]
    density: "1.75 ± 0.05 kg/l", // [cite: 509]
    cov: "Faible Cov",
    outils: "un rouleau, pinceau ou pistolet.", // [cite: 511]
    preparation: "Pour tous les travaux, les supports doivent être sains, secs.", // [cite: 515]
    longDescription: "Revêtement acrylique fluide d'usage universel extérieur, parfait pour la coloration économique des maçonneries.",
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },
  

  // ==================== EXTÉRIEUR - VERNIS ====================
  {
    id: "ext-prisma-pores",
    name: "PRISMA PORES",
        pdfUrl: "/prismacolorwebsite/fiches/PrismaPores.pdf", // <--- Le chemin vers votre fichier

    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Protection Hydro-Régulatrice",
    description: "Vernis acrylique satiné microporeux pour saturer et rehausser les chalets et menuiseries extérieures.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Protège le veinage du bois", "Filtre anti-UV de haute performance", "Hydrophobe et microporeux", "Grande facilité de maintenance"],
    image: "/prismacolorwebsite/images/PrismaPores.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Vernis acrylique satiné microporeux pour saturer et rehausser les chalets et menuiseries extérieures. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
    id: "ext-prisma-wood",
    name: "PRISMA WOOD",
        pdfUrl: "/prismacolorwebsite/fiches/PrismaWood.pdf", // <--- Le chemin vers votre fichier

    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Vitrification Extrême",
    description: "Vernis polyuréthane de qualité marine hautement polymérisé offrant un superbe fini brillant durable face aux agressions UV.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Brillant miroir très robuste", "Résistance aux embruns marins", "Absorbeurs d'UV intégrés", "Séchage régulier rapide"],
    image: "/prismacolorwebsite/images/PrismaWood.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Vernis polyuréthane de qualité marine hautement polymérisé offrant un superbe fini brillant durable face aux agressions UV. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
    id: "ext-vernis-pio",
    name: "VERNIS PIO", // J'ai gardé le nom de la classe d'origine comme demandé
    pdfUrl: "/prismacolorwebsite/fiches/PrismaVernisPolyurethane.pdf",
    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Spécial Pierre & Brique",
    description: "Vernis de finition polyuréthane bi-composant.",
    coverage: "150 à 250 g/m²",
    coverageMultiplier: 5, // Correspond à environ 5m² par kg
    dryingTime: "Sec : 2 heures",
    finishes: ["Satiné"],
    features: ["Finition polyuréthane protectrice", "Système bi-composant"], // Basé sur les caractéristiques du produit
    image: "/src/assets/images/paint_bucket_ext-vernis-pio.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Mélange : verser le composant A dans B",
    density: "1.08 ± 0.05 g/cm³", // Laissé par défaut car non spécifié
    cov: "Faible Cov",
    outils: "Rouleau",
    preparation: "Utiliser un mélangeur à faible vitesse et verser le composant A dans B avant l'application.",
    longDescription: "Vernis de finition polyuréthane bi-composant. Spécialement conçu pour une excellente résistance et durabilité.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
    id: "ext-prisma-protect",
    name: "PRISMA PROTECT",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaProtect.pdf", // <--- Le chemin vers votre fichier
    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Barrière Hydrofuge Invisible",
    description: "Traitement de protection extérieure totalement invisible et perlant protégeant des graisses et graffiti.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Totalement incolore sans brillance", "Empêche la pénétration des graisses", "Effet déperlant d'étanchéité", "Nettoyage de briques simplifié"],
    image: "/src/assets/images/paint_bucket_ext-prisma-protect.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Traitement de protection extérieure totalement invisible et perlant protégeant des graisses et graffiti. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },

  // ==================== EXTÉRIEUR - SOLUTIONS ====================
  {
    id: "ext-antifissure",
    name: "ANTIFISSURE",
        pdfUrl: "/prismacolorwebsite/fiches/PrismaAntifissure.pdf", // <--- Le chemin vers votre fichier

    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Hydro-Élastomère",
    description: "Peinture d'imperméabilisation élastomère haute élasticité, idéale pour ponter les fissures actives de façade.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Capacité de pontage jusqu'à 2.5mm", "Imperméabilité totale à l'eau liquide", "Excellente tenue aux amplitudes thermiques", "Fini mat garnissant"],
    image: "/prismacolorwebsite/images/AntiFissure.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Peinture d'imperméabilisation élastomère haute élasticité, idéale pour ponter les fissures actives de façade. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-enduit-carrelage",
    name: "ENDUIT CARRELAGE",
        pdfUrl: "/prismacolorwebsite/fiches/PrismaEnduitCarrelage.pdf", // <--- Le chemin vers votre fichier

    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Adhésion Directe Sols",
    description: "Enduit-colle étanche spécial terrasse permettant d'unifier les sols extérieures recouverts de faïence avant peinture.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Super adhérence ciment-résine", "Résistant au gel-gél extérieur", "Étanchéité secondaire adjointe", "Application à la spatule large"],
    image: "/prismacolorwebsite/images/EnduitCarrelage.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Enduit-colle étanche spécial terrasse permettant d'unifier les sols extérieures recouverts de faïence avant peinture. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-antihumidite",
    name: "ANTIHUMIDITÉ",
        pdfUrl: "/prismacolorwebsite/fiches/PrismaAntihumidite.pdf", // <--- Le chemin vers votre fichier

    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Hydrofuge Coupe-Barrière",
    description: "Traitement minéralisant hydrofuge de profondeur destiné à assainir et étanchéifier les soubassements bruts.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["S'oppose aux remontées par capillarité", "Fort pouvoir durcisseur moléculaire", "Idéal contre les dalles poreuses", "Invisible ou recouvrable"],
    image: "/prismacolorwebsite/images/Antihumidité.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Traitement minéralisant hydrofuge de profondeur destiné à assainir et étanchéifier les soubassements bruts. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-prisma-flex",
    name: "PRISMA FLEX",
    pdfUrl: "/prismacolorwebsite/fiches/PrismaFlex.pdf",
    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Étanchéité Liquide",
    description: "Résine élastique d'étanchéité liquide continue formant une membrane caoutchouteuse imperméable pour terrasses.",
    coverage: "1.5 - 2 m²/kg",
    coverageMultiplier: 1.75,
    dryingTime: "Hors poussières : 6 à 8h, Sec : 24h",
    finishes: ["Satiné"],
    features: ["Imperméable à l'eau de ruissellement", "Très bonne résistance aux intempéries", "Grande élasticité qui compense les microfissures et les fissures", "Imperméable à l'eau liquide"],
    image: "/prismacolorwebsite/images/PrismaFlex.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "1ère couche : 30 à 40 % d'eau, 2ème couche : Sans dilution",
    density: "1.25 ± 0.05 Kg/L",
    cov: "Faible Cov",
    outils: "Un rouleau ou brosse.",
    preparation: "Pour tous les travaux, les supports doivent être sains, secs.",
    longDescription: "Résine élastique d'étanchéité liquide continue formant une membrane caoutchouteuse imperméable pour terrasses.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-prisma-fibre",
    name: "PRISMA FIBRE",
        pdfUrl: "/prismacolorwebsite/fiches/CiraMineralia.pdf", // <--- Le chemin vers votre fichier

    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Mortier Armé Fibres",
    description: "Mortier de surfaçage technique armé de micro-fibres de verre synthétiques, empêchant la fissuration mécanique façades.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Résistance extrême à la traction", "Garnissage direct des éclats de béton", "Ponçage facile", "Excellent support d'accroche"],
    image: "/prismacolorwebsite/images/PrismaFibre.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Mortier de surfaçage technique armé de micro-fibres de verre synthétiques, empêchant la fissuration mécanique façades. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-izo-10",
    name: "IZO 10",
        pdfUrl: "/prismacolorwebsite/fiches/CiraMineralia.pdf", // <--- Le chemin vers votre fichier

    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Réflecteur Thermique",
    description: "Peinture d'étanchéité et d'isolation thermo-réflective, bloquant le rayonnement solaire infrarouge pour isoler les toitures.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Abaisse doucement la température intérieure", "Membrane étanche élastique continue", "Haute réflectivité solaire certifiée", "Application simple et à haut rendement"],
    image: "/src/assets/images/paint_bucket_ext-izo-10.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Peinture d'étanchéité et d'isolation thermo-réflective, bloquant le rayonnement solaire infrarouge pour isoler les toitures. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  }
];

export const MOROCCAN_COLORS: Color[] = [
  { id: "prisma-green", name: "Vert Prisma", hex: "#6ca352", category: "nature", description: "Le vert officiel Prisma, symbole d'authenticité et de nature marocaine." },
  { id: "prisma-gold", name: "Or de Fès", hex: "#d2a632", category: "chaleureux", description: "Un jaune ocre riche et lumineux, inspiré par la finesse et la splendeur de l'artisanat de Fès." },
  { id: "prisma-red", name: "Rouge Marrakech", hex: "#dc1d24", category: "chaleureux", description: "Un rouge vibrant et terreux, capturant la chaleur des remparts de la ville ocre sous le soleil couchant." },
  { id: "ocean-safi", name: "Bleu de Safi", hex: "#1e5299", category: "mineral", description: "Un bleu azur profond et captivant qui évoque la célèbre faïence de Safi." },
  { id: "dune-sahara", name: "Sable du Sahara", hex: "#e7c08a", category: "chaleureux", description: "Un ton sable chaud, apaisant et très polyvalent pour les intérieurs modernes." },
  { id: "atlas-slate", name: "Ardoise de l'Atlas", hex: "#4a535a", category: "mineral", description: "Un gris foncé majestueux et texturé, tiré des rocheuses du Haut Atlas." },
  { id: "white-moulay", name: "Blanc Moulay Idriss", hex: "#fcfcfa", category: "neutre", description: "Un blanc pur avec une touche d'ivoire très douce, apportant de l'éclat aux pièces sombres." },
  { id: "terracotta-ouarzazate", name: "Terre de Kasbah", hex: "#c87d55", category: "chaleureux", description: "Un terracotta chaleureux qui rappelle l'enduit de terre crue des Kasbahs du Sud." },
  { id: "mint-valley", name: "Menthe de l'Ourika", hex: "#a4cbb4", category: "nature", description: "Un vert de menthe poivrée pastel, relaxant, idéal pour introduire de la fraîcheur." },
  { id: "charcoal-casbah", name: "Charbon de Mejjat", hex: "#1c1d1f", category: "neutre", description: "Le noir charbon de notre charte graphique. Profond, élégant et riche." },
  { id: "pearl-rabat", name: "Brume de Rabat", hex: "#e0e3e5", category: "neutre", description: "Un gris perle lumineux inspiré de la brume côtière matinale de la capitale." },
  { id: "copper-medina", name: "Cuivre de la Médina", hex: "#b46548", category: "chaleureux", description: "Une nuance cuivrée métallique polie, douce mais pleine de caractère." }
];

export const MOCK_ROOMS: Room[] = [
  {
    id: "salon",
    name: "Salon Contemporain",
    label: "Séjour & Espace à Vivre",
    viewBox: "0 0 800 450",
    elements: [
      { id: "bg", name: "Plancher & Arrière-plan", defaultColor: "#e5dec9", d: "M 0 0 L 800 0 L 800 450 L 0 450 Z" },
      { id: "floor", name: "Sol en Parquet", defaultColor: "#a38d72", d: "M 0 320 L 800 320 L 800 450 L 0 450 Z" },
      { id: "wall-left", name: "Mur d'Accent Gauche", defaultColor: "COLOR_PLACEHOLDER", d: "M 0 0 L 220 50 L 220 320 L 0 320 Z" },
      { id: "wall-back", name: "Mur Principal", defaultColor: "COLOR_PLACEHOLDER_BG", d: "M 220 50 L 580 50 L 580 320 L 220 320 Z" },
      { id: "wall-right", name: "Mur Droit", defaultColor: "#f3f3f0", d: "M 580 50 L 800 0 L 800 320 L 580 320 Z" },
      { id: "sofa", name: "Canapé Style Marocain", defaultColor: "#2a2d34", d: "M 280 220 L 520 220 C 530 220, 540 230, 540 240 L 540 290 L 260 290 L 260 240 C 260 230, 270 220, 280 220 Z M 220 250 L 260 250 L 260 300 L 220 300 Z M 540 250 L 580 250 L 580 300 L 540 300 Z" },
      { id: "pillow-1", name: "Coussin Or fès", defaultColor: "#d2a632", d: "M 290 235 C 290 225, 330 225, 330 235 L 330 270 L 290 270 Z" },
      { id: "pillow-2", name: "Coussin Vert", defaultColor: "#6ca352", d: "M 470 235 C 470 225, 510 225, 510 235 L 510 270 L 470 270 Z" },
      { id: "lamp", name: "Suspension Cuivre", defaultColor: "#b46548", d: "M 400 50 L 400 110 M 370 110 L 430 110 L 415 130 L 385 130 Z" },
      { id: "frame", name: "Tableau Déco", defaultColor: "#ffffff", d: "M 340 70 L 460 70 L 460 150 L 340 150 Z" },
      { id: "frame-inner", name: "Contenu Tableau", defaultColor: "#e5f0e0", d: "M 350 80 L 450 80 L 450 140 L 350 140 Z" }
    ]
  },
  {
    id: "facade",
    name: "Façade Extérieure",
    label: "Riad & Villa",
    viewBox: "0 0 800 450",
    elements: [
      { id: "sky", name: "Ciel Azur", defaultColor: "#abccee", d: "M 0 0 L 800 0 L 800 450 L 0 450 Z" },
      { id: "ground", name: "Sol Pavé", defaultColor: "#939ba2", d: "M 0 350 L 800 350 L 800 450 L 0 450 Z" },
      { id: "main-wall", name: "Corps de Façade", defaultColor: "COLOR_PLACEHOLDER", d: "M 80 80 L 720 80 L 720 350 L 80 350 Z" },
      { id: "roof", name: "Toiture Tuiles vertes", defaultColor: "#325732", d: "M 60 80 L 740 80 L 700 45 L 100 45 Z" },
      { id: "door-frame", name: "Encadrement Arche", defaultColor: "COLOR_PLACEHOLDER_ALT", d: "M 340 180 C 340 130, 460 130, 460 180 L 460 350 L 340 350 Z" },
      { id: "door", name: "Porte Sculptée", defaultColor: "#58200c", d: "M 355 190 C 355 155, 445 155, 445 190 L 445 350 L 355 350 Z" },
      { id: "window-l", name: "Fenêtre Gauche", defaultColor: "#eaeceb", d: "M 180 140 L 260 140 L 260 220 L 180 220 Z" },
      { id: "window-r", name: "Fenêtre Droite", defaultColor: "#eaeceb", d: "M 540 140 L 620 140 L 620 220 L 540 220 Z" },
      { id: "window-bar-l", name: "Grilles Gauche", defaultColor: "#111111", d: "M 180 180 L 260 180 M 220 140 L 220 220" },
      { id: "window-bar-r", name: "Grilles Droite", defaultColor: "#111111", d: "M 540 180 L 620 180 M 580 140 L 580 220" },
      { id: "plant-pot", name: "Vase Terracotta", defaultColor: "#b05427", d: "M 290 310 L 320 310 L 315 350 L 295 350 Z" },
      { id: "plant-green", name: "Plante Menthe", defaultColor: "#417441", d: "M 285 295 C 295 285, 315 285, 325 295 C 335 285, 320 270, 305 270 C 290 270, 275 285, 285 295 Z" }
    ]
  },
  {
    id: "chambre",
    name: "Chambre à Coucher",
    label: "Suite Parentale ou Enfant",
    viewBox: "0 0 800 450",
    elements: [
      { id: "bg", name: "Plafond", defaultColor: "#fafafa", d: "M 0 0 L 800 0 L 800 450 L 0 450 Z" },
      { id: "floor", name: "Sol Carrelage beige", defaultColor: "#eae3d2", d: "M 0 350 L 800 350 L 800 450 L 0 450 Z" },
      { id: "headboard-wall", name: "Tête de lit (Mur d'appui)", defaultColor: "COLOR_PLACEHOLDER", d: "M 120 40 L 680 40 L 680 350 L 120 350 Z" },
      { id: "wall-left", name: "Mur Gauche", defaultColor: "#eef2e6", d: "M 0 0 L 120 40 L 120 350 L 0 350 Z" },
      { id: "wall-right", name: "Mur Droit", defaultColor: "#fbf9f4", d: "M 680 40 L 800 0 L 800 350 L 680 350 Z" },
      { id: "bed", name: "Sommier Lit", defaultColor: "#b2abab", d: "M 230 260 L 570 260 L 570 350 L 230 350 Z" },
      { id: "headboard", name: "Tête de lit Cuir", defaultColor: "#6c4d37", d: "M 210 180 L 590 180 L 590 260 L 210 260 Z" },
      { id: "blanket", name: "Couverture de lit", defaultColor: "#4f6e5a", d: "M 240 280 L 560 280 L 560 350 L 240 350 Z" },
      { id: "pillows", name: "Oreillers", defaultColor: "#fcfcfa", d: "M 260 220 L 370 220 L 370 260 L 260 260 Z M 430 220 L 540 220 L 540 260 L 430 260 Z" },
      { id: "pillows-acc", name: "Coussinet Ocre", defaultColor: "#d2a632", d: "M 350 240 L 390 240 L 410 270 L 370 270 Z" },
      { id: "shelf", name: "Table de chevet bois", defaultColor: "#93633e", d: "M 140 290 L 190 290 L 190 350 L 140 350 Z M 610 290 L 660 290 L 660 350 L 610 350 Z" }
    ]
  }
];