export interface Product {
  id: string;
  name: string;
  category: 'interior' | 'exterior' | 'decor' | 'special';
  subCategory?: string;
  line: string;
  description: string;
  coverage: string; 
  coverageMultiplier: number; 
  dryingTime: string; 
  finishes: string[]; 
  tag: string;
  features: string[];
  image: string;
  fallbackImage: string;
  dilution: string;
  density: string;
  cov: string;
  outils: string;
  preparation: string;
  longDescription: string;
  usage: string[];
  pdfUrl?: string;
}

export interface Color {
  id: string;
  name: string;
  hex: string;
  category: 'chaleureux' | 'mineral' | 'nature' | 'neutre';
  description: string;
}

export interface Room {
  id: string;
  name: string;
  label: string;
  viewBox: string;
  elements: { id: string; name: string; defaultColor: string; d: string }[];
}

export const PRODUCTS_DB: Product[] = [
  // ==================== INTÉRIEUR - DÉCO ====================
  {
    id: "int-chromia",
    name: "CHROMIA",
    pdfUrl: "/prisma-color-website/fiches/chromia.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Effet nacré",
    description: "Peinture décorative haut de gamme à effet velours mat soyeux qui magnifie l'éclairage intérieur.",
    coverage: "4 m²/KG par couche",
    coverageMultiplier: 4, // La valeur utilisée par la formule (m²/kg)
    features: ["Bon pouvoir couvrant. ", "Très facile à appliquer"],
    dryingTime: "Hors poussières: 1H, Recouvrable : 4H",
    finishes: ["Marbré", "satiné"],
    image: "/prisma-color-website/images/Chromia.png",
    fallbackImage: "/src/assets/images/Chromia.png",
    dilution: "5 à 10 % avec d'eau à 25 °C",
    density: "1.6 ± 0.05 kg/l",
    cov: "Faible Cov ",
    outils: " Taloche inox ou couteau à enduire.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "CHROMIA est une peinture décorative écologique, offrant un aspect unique grâce à sa capacité à refléter la lumière sous tous les angles, apportant ainsi une touche élégante et lumineuse. Idéale pour créer une ambiance douce et raffinée.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-cira-mineralia",
    name: "CIRA MINERALIA",
    pdfUrl: "/prisma-color-website/fiches/CiraMineralia.pdf", // <--- Le chemin vers votre fichier
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Tadelakt",
    description: " vernis acrylique en phase aqueuse, d'aspect nacré et mat, conçu pour la protection et la décoration des produits décoratifs",
    coverage: "12 à 14 m²/l selon la porosité du support.",
    coverageMultiplier: 13,
    dryingTime: "Sec : 2h, Hors poussière : 1H",
    finishes: ["Mat", "Nacré"],
    features: ["Sans odeur", "Très facile à appliquer.", "Disponible  en mate et nacré"],
    image: "/prisma-color-website/images/CiraMineralia.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: " un deuxième test 1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Enduit minéral décoratif haute performance à la chaux éteinte pour effets texturés brossés ou lissés. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-fluorina",
    name: "FLUORINA",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Mat Absolu Profond",
    description: "Peinture de prestige d'aspect mat profond hautement réfléchissante, idéale pour plafonds et surfaces unies.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Reflets anti-reprise absolus", "Blancheur lumineuse incomparable", "Opacité dès la première couche", "Fini de très haute précision"],
    image: "/prisma-color-website/images/Fluorina.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Peinture de prestige d'aspect mat profond hautement réfléchissante, idéale pour plafonds et surfaces unies. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-vega-star",
    name: "VEGA STAR",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Finition Scintillante",
    description: "Finition transparente pailletée capturant et réfléchissant la lumière artificielle pour vos murs d'accent.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Paillettes fines irisées", "Personnalisation haut de gamme", "S'applique sur tous fonds teintés", "Effet féerique sous spots"],
    image: "/prisma-color-website/images/VegaStar.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Finition transparente pailletée capturant et réfléchissant la lumière artificielle pour vos murs d'accent. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-beton-a-cire",
    name: "BÉTON À CIRÉ",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Effet Micro-Ciment",
    description: "Enduit décoratif aspect béton ciré contemporain lissé pour mobilier, sols et murs intérieurs d'architectes.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Dureté de surface exceptionnelle", "Esthétique industrielle épurée", "Épaisseur millimétrique fluide", "Imperméable après cirage"],
    image: "/prisma-color-website/images/Vide.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Enduit décoratif aspect béton ciré contemporain lissé pour mobilier, sols et murs intérieurs d'architectes. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-onyx",
    name: "ONYX",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Sable Métallisé Brillant",
    description: "Revêtement décoratif perlé offrant de fabuleux effets sablés scintillants et de somptueuses nuances ténébreuses.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Texture sablée délicate", "Reflets nacrés profonds", "Facilité de retouche", "Masque les micro-imperfections"],
    image: "/prisma-color-website/images/Onyx.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Revêtement décoratif perlé offrant de fabuleux effets sablés scintillants et de somptueuses nuances ténébreuses. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-prisma-cire",
    name: "PRISMA CIRE",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Cire de Protection",
    description: "Cire d'abeille et de protection transparente fluide pour sceller, faire briller et imperméabiliser vos stucco et enduits.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Éclat naturel prononcé", "Effet déperlant protecteur", "Facilite l'entretien courant", "Formule écologique respirante"],
    image: "/prisma-color-website/images/Vide.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Cire d'abeille et de protection transparente fluide pour sceller, faire briller et imperméabiliser vos stucco et enduits. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-iridium",
    name: "IRIDIUM",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Reflets Irisés",
    description: "Peinture décorative métallique haut de gamme à effets irisés changeant de couleur selon l'orientation de la lumière.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Fini satiné métallisé", "Chatoiement de couleurs unique", "Séchage ultra-rapide", "Résistant au lavage doux"],
    image: "/prisma-color-website/images/Iridium.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Peinture décorative métallique haut de gamme à effets irisés changeant de couleur selon l'orientation de la lumière. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-mineralia",
    name: "MINERALIA",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Ocre Mat Éco",
    description: "Peinture mate minérale écologique formulée traditionnellement à la chaux et silicates naturels pour intérieurs sains.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Absence de solvants chimiques", "Assainit l'air intérieur", "Finition mate terreuse vintage", "Excellente perspirance durable"],
    image: "/prisma-color-website/images/Mineralia.png",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Peinture mate minérale écologique formulée traditionnellement à la chaux et silicates naturels pour intérieurs sains. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-prisma-teinte",
    name: "PRISMA TEINTE",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Colorant Universel",
    description: "Système de colorants universels à haute concentration pour teinter et personnaliser avec précision toutes les bases acryliques.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Pigments minéraux inaltérables", "Compatibilité totale assurée", "Stabilité absolue de la couleur", "Formule super-concentrée"],
    image: "/src/assets/images/regenerated_image_1780776524454.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Système de colorants universels à haute concentration pour teinter et personnaliser avec précision toutes les bases acryliques. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "int-prisma-lux",
    name: "PRISMA LUX",
    category: "interior",
    subCategory: "DÉCO",
    line: "Gamme Déco",
    tag: "Laque Brillante Prestige",
    description: "Laque glycérophtalique brillante tendue de très haut standing, offrant un aspect miroir étincelant hyper durable.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Satiné", "Effet Texturé", "Velouté"],
    features: ["Aspect tendu miroir parfait", "Garnissant et couvrant extrême", "Grande dureté anti-rayures", "Lessivage intensif à volonté"],
    image: "/src/assets/images/regenerated_image_1780776524863.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Laque glycérophtalique brillante tendue de très haut standing, offrant un aspect miroir étincelant hyper durable. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },

  // ==================== INTÉRIEUR - IMPRESSION ====================
  {
    id: "int-prisma-prim-extra",
    name: "PRISMA PRIM EXTRA",
    category: "interior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression",
    tag: "Impression Universelle",
    description: "Impression universelle régulatrice à base de copolymères acryliques de haute opacité pour murs et plafonds sains.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Excellente adhérence", "Bloque la porosité de fond", "Garnissant et couvrant initial", "Application simple au rouleau"],
    image: "/prisma-color-website/images/PrismaPrimExtra.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Impression universelle régulatrice à base de copolymères acryliques de haute opacité pour murs et plafonds sains. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },
  {
    id: "int-prisma-blanc-fix",
    name: "PRISMA BLANC FIX",
    category: "interior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression",
    tag: "Fixateur d'Opacité",
    description: "Émulsion durcissante blanche à fort pouvoir opacifiant pour saturer les supports absorbants en une seule passe.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Évite les surconsommations", "Homogénéise le support", "Blancheur d'accroche idéale", "Sans odeur incommodante"],
    image: "/prisma-color-website/images/BlancFixe.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Émulsion durcissante blanche à fort pouvoir opacifiant pour saturer les supports absorbants en une seule passe. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },
  {
    id: "int-prisma-fondo",
    name: "PRISMA FONDO",
    category: "interior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression",
    tag: "Primaire Texturé",
    description: "Sous-couche d'accroche grainée ou micro-sablée, indispensable pour la dépose mécanique des enduits à effets décoratifs.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Crée une accroche rugueuse", "Facilite l'application sur plâtre", "Empêche le glissement d'enduit", "Haute teneur en charges solides"],
    image: "/prisma-color-website/images/PrismaFondo.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Sous-couche d'accroche grainée ou micro-sablée, indispensable pour la dépose mécanique des enduits à effets décoratifs. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },

  // ==================== INTÉRIEUR - ENDUIT ====================
  {
    id: "int-prisma-pate",
    name: "PRISMA PATE",
    category: "interior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits",
    tag: "Enduit Prêt à l'Emploi",
    description: "Enduit en pâte fluide prêt à l'emploi en seaux pour le ratissage total et la finition soignée de vos cloisons.",
    coverage: "0.8 - 1.5 kg/m² selon support",
    coverageMultiplier: 1.2,
    dryingTime: "Sec complet : 12h, Recouvrable : 24h",
    finishes: ["Mat très fin"],
    features: ["Glisse inégalable sous la lame", "Ponçage extrêmement aisé", "Fini lisse et doux au toucher", "Rembouche les micro-porosités"],
    image: "/prisma-color-website/images/PrismaPate.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Prêt à l'emploi en pâte onctueuse.",
    density: "1.75 ± 0.05 g/cm³",
    cov: "< 2 g/L (Zéro COV)",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "Enduit en pâte fluide prêt à l'emploi en seaux pour le ratissage total et la finition soignée de vos cloisons. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },
  {
    id: "int-prisma-pret",
    name: "PRISMA PRET",
    category: "interior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits",
    tag: "Poudre Rebouchage",
    description: "Enduit multi-usage formule poudre à haut extrait sec, parfait pour le rebouchage rapide des fissures et trous de fixation.",
    coverage: "0.8 - 1.5 kg/m² selon support",
    coverageMultiplier: 1.2,
    dryingTime: "Sec complet : 12h, Recouvrable : 24h",
    finishes: ["Mat très fin"],
    features: ["Séchage sans retrait", "Prise contrôlée et rapide", "Grande dureté de rapiéçage", "Facile de mise en œuvre"],
    image: "/prisma-color-website/images/PrismaPret.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Prêt à l'emploi en pâte onctueuse.",
    density: "1.75 ± 0.05 g/cm³",
    cov: "< 2 g/L (Zéro COV)",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "Enduit multi-usage formule poudre à haut extrait sec, parfait pour le rebouchage rapide des fissures et trous de fixation. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },
  {
    id: "int-prisma-stop",
    name: "PRISMA STOP",
    category: "interior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits",
    tag: "Barrière Anti-Sulfate",
    description: "Enduit barrière à séchage rapide bloquant activement l'humidité, le salpêtre et les taches d'oxydation métallique.",
    coverage: "0.8 - 1.5 kg/m² selon support",
    coverageMultiplier: 1.2,
    dryingTime: "Sec complet : 12h, Recouvrable : 24h",
    finishes: ["Mat très fin"],
    features: ["Barrière de protection étanche", "Permet de peindre sur zones sèches", "Bloque l'éclosion du salpêtre", "Adhérence forte multi-supports"],
    image: "/src/assets/images/regenerated_image_1780776529269.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Prêt à l'emploi en pâte onctueuse.",
    density: "1.75 ± 0.05 g/cm³",
    cov: "< 2 g/L (Zéro COV)",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "Enduit barrière à séchage rapide bloquant activement l'humidité, le salpêtre et les taches d'oxydation métallique. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },

  // ==================== INTÉRIEUR - VERNIS ====================
  {
    id: "int-prisma-pores",
    name: "PRISMA PORES",
    category: "interior",
    subCategory: "VERNIS",
    line: "Gamme Vernis",
    tag: "Saturateur Hydro-Régulateur",
    description: "Vernis isolant microporeux transparent destiné à la protection de toute essence de bois d'ébénisterie intérieure.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Respecte le toucher naturel", "Excellente élasticité", "Résistant à l'usure de contact", "Imperméabilisation de surface"],
    image: "/prisma-color-website/images/PrismaPores.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Vernis isolant microporeux transparent destiné à la protection de toute essence de bois d'ébénisterie intérieure. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
    id: "int-prisma-wood",
    name: "PRISMA WOOD",
    category: "interior",
    subCategory: "VERNIS",
    line: "Gamme Vernis",
    tag: "Polyuréthane Ultra-Dureté",
    description: "Vernis polyuréthane monocomposant brillant formulé pour la vitrification des parquets, escaliers et tables d'art.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Résistance totale aux rayures", "Fini de haut poli mirifique", "Imperméabilité absolue aux liquides", "Anti-jaunissement renforcé"],
    image: "/src/assets/images/regenerated_image_1780776530905.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Vernis polyuréthane monocomposant brillant formulé pour la vitrification des parquets, escaliers et tables d'art. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },

  // ==================== INTÉRIEUR - HYGIÈNE ====================
  {
    id: "int-peinture-antibacterienne",
    name: "PEINTURE ANTIBACTÉRIENNE",
    category: "interior",
    subCategory: "HYGIÈNE",
    line: "Gamme Hygiène",
    tag: "Ions d'Argent Actifs",
    description: "Peinture acrylique mate désinfectante, enrichie en ions d'argent détruisant les virus et bactéries au contact.",
    coverage: "10-11 m²/L par couche",
    coverageMultiplier: 10.5,
    dryingTime: "Sec : 1.5h, Recouvrable : 6h",
    finishes: ["Velouté", "Satiné Hygiénique"],
    features: ["Protection active permanente 24h", "Résiste aux lavages désinfectants", "Certifié contact alimentaire", "Idéal pour crèches et hôpitaux"],
    image: "/src/assets/images/regenerated_image_1780776530600.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Eau claire : 5% à 10% maximum.",
    density: "1.45 ± 0.05 g/cm³",
    cov: "< 8 g/L (Certifié anti-microbien)",
    outils: "Rouleau microfibre, brosse à rechampir.",
    preparation: "Laver et désinfecter le support si présence antérieure de moisissures.",
    longDescription: "Peinture acrylique mate désinfectante, enrichie en ions d'argent détruisant les virus et bactéries au contact. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Milieux hospitaliers", "Chambres d'enfants", "Cuisines et crèches"]
  },

  // ==================== INTÉRIEUR - ACRYLIQUE ====================
  {
    id: "int-prisma-plast",
    name: "PRISMA PLAST",
    category: "interior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques",
    tag: "Acrylique Garnissant Fort",
    description: "Peinture acrylique à forte viscosité créant un film lessivable hyper-robuste. Recommandée pour tous couloirs et écoles.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 2h, Recouvrable : 6h",
    finishes: ["Satiné", "Mat velouté"],
    features: ["Haut rendement de masquage", "Film plastique Lessivable", "Résiste aux frottements réguliers", "Séchage commode et rapide"],
    image: "/prisma-color-website/images/PrismaPlast.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Eau claire : 10% max.",
    density: "1.41 ± 0.05 g/cm³",
    cov: "< 12 g/L (Haute lessivabilité)",
    outils: "Rouleau polyester 12mm, brosse, Airless.",
    preparation: "Appliquer une sous-couche compatible pour homogénéiser l'absorption.",
    longDescription: "Peinture acrylique à forte viscosité créant un film lessivable hyper-robuste. Recommandée pour tous couloirs et écoles. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },
  {
    id: "int-prisma-vinyl",
    name: "PRISMA VINYL",
    category: "interior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques",
    tag: "Finition Souple de Tradition",
    description: "Peinture traditionnelle à base de copolymères vinyliques offrant un excellent rapport pouvoir couvrant / prix.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 2h, Recouvrable : 6h",
    finishes: ["Satiné", "Mat velouté"],
    features: ["Blancheur mate respirante", "Idéal sur plaques de plâtre", "Bonne opacité en deux passes", "Application fluide sans traînées"],
    image: "/prisma-color-website/images/PrismaVinyl.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Eau claire : 10% max.",
    density: "1.41 ± 0.05 g/cm³",
    cov: "< 12 g/L (Haute lessivabilité)",
    outils: "Rouleau polyester 12mm, brosse, Airless.",
    preparation: "Appliquer une sous-couche compatible pour homogénéiser l'absorption.",
    longDescription: "Peinture traditionnelle à base de copolymères vinyliques offrant un excellent rapport pouvoir couvrant / prix. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },
  {
    id: "int-ecologia",
    name: "ECOLOGIA",
    category: "interior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques",
    tag: "Zéro COV Certifié",
    description: "Peinture écologique d'aspect mat soyeux exempte de solvant et de conservateur allergique pour l'assainissement de vos pièces.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 2h, Recouvrable : 6h",
    finishes: ["Satiné", "Mat velouté"],
    features: ["Label environnemental d'excellence", "Qualité d'air classe A+", "Recommandé pour personnes sensibles", "Excellente lavabilité veloutée"],
    image: "/prisma-color-website/images/Ecologia.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Eau claire : 10% max.",
    density: "1.41 ± 0.05 g/cm³",
    cov: "< 12 g/L (Haute lessivabilité)",
    outils: "Rouleau polyester 12mm, brosse, Airless.",
    preparation: "Appliquer une sous-couche compatible pour homogénéiser l'absorption.",
    longDescription: "Peinture écologique d'aspect mat soyeux exempte de solvant et de conservateur allergique pour l'assainissement de vos pièces. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },

  // ==================== INTÉRIEUR - SOLUTIONS ====================
  {
    id: "int-enduit-carrelage",
    name: "ENDUIT CARRELAGE",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Rénovation Directe Faïence",
    description: "Enduit d'égalisation et d'accroche étanche conçu pour masquer directement les joints de carrelage intérieurs.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Adhérence totale sur verre et céramique", "Évite d'enlever l'ancien carrelage", "Préparation résiliente", "Garantit des murs intérieurs plats"],
    image: "/prisma-color-website/images/EnduitCarrelage.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Enduit d'égalisation et d'accroche étanche conçu pour masquer directement les joints de carrelage intérieurs. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-antifissure",
    name: "ANTIFISSURE",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Élastique Anti-Fissures",
    description: "Traitement acrylique souple de rebouchage pour réparations de fissures actives intérieures sujettes aux micro-mouvements.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Allongement exceptionnel", "Suit les mouvements de dilatation", "Recouvrable par toutes finitions", "Excellente tenue dans le temps"],
    image: "/prisma-color-website/images/AntiFissure.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Traitement acrylique souple de rebouchage pour réparations de fissures actives intérieures sujettes aux micro-mouvements. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-antihumidite",
    name: "ANTIHUMIDITÉ",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Bloqueur d'Infiltration",
    description: "Peinture solvantée d'étanchéité intérieure bloquant activement l'humidité dans les caves, sous-sols et buanderies.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Directement applicable sur fond humide", "Permet l'évaporation saine de l'eau", "Bloque l'humidité de capillarité", "Traitement curatif absolu"],
    image: "/prisma-color-website/images/Antihumidité.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Peinture solvantée d'étanchéité intérieure bloquant activement l'humidité dans les caves, sous-sols et buanderies. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-fongex",
    name: "FONGEX",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Assainissant Anti-Moisissure",
    description: "Solution liquide curative à large spectre pour éliminer et désinfecter les moisissures et lichens des zones obscures humides.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Action destructrice rapide", "Empêche la réapparition des mousses", "Pénètre profondément le support", "Facile d'application par brosse"],
    image: "/prisma-color-website/images/Fongex.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Solution liquide curative à large spectre pour éliminer et désinfecter les moisissures et lichens des zones obscures humides. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-prima-fix",
    name: "PRIMA FIX",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Fixateur Fort Solvanté",
    description: "Fixateur de fond incolore en solvant, conçu pour agglomérer durcir et fixer les plâtres farineux ou friables.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Pénétration sub-porale intense", "Consolide les bétons poreux", "Améliore le rendement des finitions", "Haute tenue aux alcalis"],
    image: "/src/assets/images/paint_bucket_int-prima-fix.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Fixateur de fond incolore en solvant, conçu pour agglomérer durcir et fixer les plâtres farineux ou friables. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "int-epoxy",
    name: "EPOXY",
    category: "interior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions",
    tag: "Résine Sol Bi-Composante",
    description: "Système époxy fluide auto-lissant bi-composant haute performance pour sols intérieurs d'habitations d'ateliers.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Dureté vitreuse ultra-solide", "Résistance chimique aux hydrocarbures", "Aspect brillant impeccable", "Zéro jaunissement sous verre"],
    image: "/src/assets/images/regenerated_image_1780776539099.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Système époxy fluide auto-lissant bi-composant haute performance pour sols intérieurs d'habitations d'ateliers. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },

  // ==================== EXTÉRIEUR - DÉCO ====================
  {
    id: "ext-effet-beton",
    name: "EFFET BETON",
    category: "exterior",
    subCategory: "DÉCO",
    line: "Gamme Déco Facade",
    tag: "Brut / Contemporain",
    description: "Enduit acrylique garnissant extérieur reproduisant parfaitement l'effet authentique du béton brut de décoffrage.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Mat structuré", "Aspect Béton"],
    features: ["Rendu architectural contemporain", "Masque les spectres de briques", "Protection anti-UV renforcée", "Haute perspirance à la vapeur"],
    image: "/src/assets/images/regenerated_image_1780776538686.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Enduit acrylique garnissant extérieur reproduisant parfaitement l'effet authentique du béton brut de décoffrage. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "ext-monocouche",
    name: "MONOCOUCHE",
    category: "exterior",
    subCategory: "DÉCO",
    line: "Gamme Déco Facade",
    tag: "Crépi Minéral Moderne",
    description: "Revêtement d'imperméabilisation monocouche à base de chaux et charges de quartz pour la mise en valeur des villas.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Mat structuré", "Aspect Béton"],
    features: ["Décoration en une seule passe", "Imperméabilisation certifiée", "Résistance au grattage", "Disponible en teintes chaudes du Maroc"],
    image: "/src/assets/images/regenerated_image_1780776539917.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Revêtement d'imperméabilisation monocouche à base de chaux et charges de quartz pour la mise en valeur des villas. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },
  {
    id: "ext-prisma-rex",
    name: "PRISMA REX",
    category: "exterior",
    subCategory: "DÉCO",
    line: "Gamme Déco Facade",
    tag: "Revêtement Plastique Épais",
    description: "Revêtement plastique lourd (RPE) riche en quartz colorés pour la protection robuste de façades côtières.",
    coverage: "5-7 m²/L par couche",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Recouvrable : 24h",
    finishes: ["Mat structuré", "Aspect Béton"],
    features: ["Excellente compensation des facettes", "Finition grésée très robuste", "Barrière imperméable absolue", "Épaisseur mécanique anti-chocs"],
    image: "/src/assets/images/regenerated_image_1780776539392.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_decor_1780770364551.png",
    dilution: "Prêt à l'emploi. Dilution à l'eau 5% max.",
    density: "1.62 ± 0.05 g/cm³",
    cov: "< 10 g/L (Norme Environnementale Alkyde-Silice)",
    outils: "Spatule, platoir inox, brosse à effet, spalter.",
    preparation: "Le support doit être rigoureusement lisse, plan, sain et parfaitement enduit.",
    longDescription: "Revêtement plastique lourd (RPE) riche en quartz colorés pour la protection robuste de façades côtières. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Murs d'accent et niches", "Halls de palaces", "Salons traditionnels et modernes"]
  },

  // ==================== EXTÉRIEUR - IMPRESSION ====================
  {
    id: "ext-prisma-prim-extra",
    name: "PRISMA PRIM EXTRA",
    category: "exterior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression Facade",
    tag: "Primaire Hydrofuge",
    description: "Sous-couche acrylique hydrofuge extérieure d'accrochage à fort pouvoir régulateur de porosité maçonnerie.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Améliore le glissement de finition", "Hydrophobe de surface", "Pénétration optimale des enduits", "Réduit la consommation de peinture"],
    image: "/prisma-color-website/images/PrismaPrimExtra.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Sous-couche acrylique hydrofuge extérieure d'accrochage à fort pouvoir régulateur de porosité maçonnerie. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },
  {
    id: "ext-blanc-fixe",
    name: "BLANC FIXE",
    category: "exterior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression Facade",
    tag: "Régulation Blancheur",
    description: "Primaire et bloqueur d'alcalis à fort extrait sec blanc, excellent pour stabiliser les façades extérieures sales ou anciennes.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Neutralise la laitance du béton", "Opacité immense sur fonds foncés", "Excellente tenue aux sels marins", "Améliore la durabilité extérieure"],
    image: "/prisma-color-website/images/BlancFixe.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Primaire et bloqueur d'alcalis à fort extrait sec blanc, excellent pour stabiliser les façades extérieures sales ou anciennes. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },
  {
    id: "ext-prima-fixe",
    name: "PRIMA FIXE",
    category: "exterior",
    subCategory: "IMPRESSION",
    line: "Gamme Impression Facade",
    tag: "Fixateur de Maçonnerie",
    description: "Impression durcissante solvantée à forte capacité d'accrochage pour resserrer et agréger les enduits farineux.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 1h, Recouvrable : 4h",
    finishes: ["Opale Mat"],
    features: ["Excellente pénétration micrométrique", "Bloque l'efflorescence alcaline", "Idéal avant les peintures de façade", "Applicable en conditions humides"],
    image: "/src/assets/images/regenerated_image_1780776541760.jpg",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Eau claire : 10% à 15% pour pénétration optimale.",
    density: "1.49 ± 0.05 g/cm³",
    cov: "< 5 g/L (Haute performance écologique)",
    outils: "Rouleau microfibre 12mm, brosse, pistolet Airless.",
    preparation: "Brosser et dépoussiérer les maçonneries neuves avant application du primaire.",
    longDescription: "Impression durcissante solvantée à forte capacité d'accrochage pour resserrer et agréger les enduits farineux. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Fonds poreux", "Plaques de plâtre", "Supports neufs absorbants"]
  },

  // ==================== EXTÉRIEUR - ENDUIT ====================
  {
    id: "ext-enduit-facade-lisse",
    name: "ENDUIT FACADE LISSE",
    category: "exterior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits Facade",
    tag: "Lissage Plat Parfait",
    description: "Enduit d'égalisation et de ratissage extérieur formulé pour niveler parfaitement les façades rugueuses.",
    coverage: "0.8 - 1.5 kg/m² selon support",
    coverageMultiplier: 1.2,
    dryingTime: "Sec complet : 12h, Recouvrable : 24h",
    finishes: ["Mat très fin"],
    features: ["Résistance totale aux intempéries", "Ponçage très simple", "Nivellement précis au mortier", "Excellente souplesse d'application"],
    image: "/prisma-color-website/images/EnduitFacadeLisse.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Prêt à l'emploi en pâte onctueuse.",
    density: "1.75 ± 0.05 g/cm³",
    cov: "< 2 g/L (Zéro COV)",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "Enduit d'égalisation et de ratissage extérieur formulé pour niveler parfaitement les façades rugueuses. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },
  {
    id: "ext-enduit-facade-130",
    name: "ENDUIT FACADE 130",
    category: "exterior",
    subCategory: "ENDUIT",
    line: "Gamme Enduits Facade",
    tag: "Garnissant Mortier Lourd",
    description: "Enduit cimenteux de ragréage extérieur à fort pouvoir garnissant permettant de reboucher jusqu'à 5mm par couche.",
    coverage: "0.8 - 1.5 kg/m² selon support",
    coverageMultiplier: 1.2,
    dryingTime: "Sec complet : 12h, Recouvrable : 24h",
    finishes: ["Mat très fin"],
    features: ["Adhérence extraordinaire sur béton brut", "Aucun affaissement de matière", "Retrait réduit contrôlé", "Haut rendement de rattrapage"],
    image: "/prisma-color-website/images/EnduitFacade130.png",
    fallbackImage: "/src/assets/images/paint_bucket_habitat_1780770319051.png",
    dilution: "Prêt à l'emploi en pâte onctueuse.",
    density: "1.75 ± 0.05 g/cm³",
    cov: "< 2 g/L (Zéro COV)",
    outils: "Lame à enduire, platoir en acier inoxydable.",
    preparation: "Nettoyer le support, combler au préalable les fissures majeures.",
    longDescription: "Enduit cimenteux de ragréage extérieur à fort pouvoir garnissant permettant de reboucher jusqu'à 5mm par couche. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Rembouchage et lissage", "Préparation des murs intérieurs/extérieurs"]
  },

  // ==================== EXTÉRIEUR - ACRYLIQUE ====================
  {
    id: "ext-prisma-plast",
    name: "PRISMA PLAST",
    category: "exterior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques Facade",
    tag: "Peinture Plastique Durable",
    description: "Peinture acrylique garnissante de haute technicité très résistante aux frottements sablonneux et au lessivage naturel.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 2h, Recouvrable : 6h",
    finishes: ["Satiné", "Mat velouté"],
    features: ["Protection haut de gamme", "Rendement de coloration éclatant", "Traité fongicide et algicide", "Film robuste lessivable"],
    image: "/prisma-color-website/images/PrismaPlast.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Eau claire : 10% max.",
    density: "1.41 ± 0.05 g/cm³",
    cov: "< 12 g/L (Haute lessivabilité)",
    outils: "Rouleau polyester 12mm, brosse, Airless.",
    preparation: "Appliquer une sous-couche compatible pour homogénéiser l'absorption.",
    longDescription: "Peinture acrylique garnissante de haute technicité très résistante aux frottements sablonneux et au lessivage naturel. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },
  {
    id: "ext-prisma-vinyl",
    name: "PRISMA VINYL",
    category: "exterior",
    subCategory: "ACRYLIQUE",
    line: "Gamme Acryliques Facade",
    tag: "Finition Résistante Éco",
    description: "Revêtement acrylique fluide d'usage universel extérieur, parfait pour la coloration économique des maçonneries.",
    coverage: "9-11 m²/L par couche",
    coverageMultiplier: 10,
    dryingTime: "Sec au toucher : 2h, Recouvrable : 6h",
    finishes: ["Satiné", "Mat velouté"],
    features: ["Haute blancheur de façade", "Excellente respirabilité", "Application au rouleau méché facile", "Tenue de teinte éprouvée"],
    image: "/prisma-color-website/images/PrismaVinyl.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Eau claire : 10% max.",
    density: "1.41 ± 0.05 g/cm³",
    cov: "< 12 g/L (Haute lessivabilité)",
    outils: "Rouleau polyester 12mm, brosse, Airless.",
    preparation: "Appliquer une sous-couche compatible pour homogénéiser l'absorption.",
    longDescription: "Revêtement acrylique fluide d'usage universel extérieur, parfait pour la coloration économique des maçonneries. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Pièces de vie principales", "Cuisines et circulations", "Bâtiments tertiaires"]
  },

  // ==================== EXTÉRIEUR - VERNIS ====================
  {
    id: "ext-prisma-pores",
    name: "PRISMA PORES",
    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Protection Hydro-Régulatrice",
    description: "Vernis acrylique satiné microporeux pour saturer et rehausser les chalets et menuiseries extérieures.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Protège le veinage du bois", "Filtre anti-UV de haute performance", "Hydrophobe et microporeux", "Grande facilité de maintenance"],
    image: "/prisma-color-website/images/PrismaPores.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Vernis acrylique satiné microporeux pour saturer et rehausser les chalets et menuiseries extérieures. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
    id: "ext-prisma-wood",
    name: "PRISMA WOOD",
    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Vitrification Extrême",
    description: "Vernis polyuréthane de qualité marine hautement polymérisé offrant un superbe fini brillant durable face aux agressions UV.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Brillant miroir très robuste", "Résistance aux embruns marins", "Absorbeurs d'UV intégrés", "Séchage régulier rapide"],
    image: "/prisma-color-website/images/PrismaWood.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Vernis polyuréthane de qualité marine hautement polymérisé offrant un superbe fini brillant durable face aux agressions UV. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
    id: "ext-vernis-pio",
    name: "VERNIS PIO",
    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Spécial Pierre & Brique",
    description: "Vernis acrylique brillant protecteur conçu spécifiquement pour étanchéifier et revivifier les parements en pierre.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Effet mouillé très esthétique", "Empêche l'apparition de lichens", "Excellente adhérence minérale", "Résistance au soleil aride"],
    image: "/src/assets/images/paint_bucket_ext-vernis-pio.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Vernis acrylique brillant protecteur conçu spécifiquement pour étanchéifier et revivifier les parements en pierre. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },
  {
    id: "ext-prisma-protect",
    name: "PRISMA PROTECT",
    category: "exterior",
    subCategory: "VERNIS",
    line: "Gamme Vernis Facade",
    tag: "Barrière Hydrofuge Invisible",
    description: "Traitement de protection extérieure totalement invisible et perlant protégeant des graisses et graffiti.",
    coverage: "10-12 m²/L par couche",
    coverageMultiplier: 11,
    dryingTime: "Sec au toucher : 3h, Recouvrable : 8h",
    finishes: ["Brillant Céleste", "Satiné Soyeux"],
    features: ["Totalement incolore sans brillance", "Empêche la pénétration des graisses", "Effet déperlant d'étanchéité", "Nettoyage de briques simplifié"],
    image: "/src/assets/images/paint_bucket_ext-prisma-protect.png",
    fallbackImage: "/src/assets/images/paint_bucket_velours_1780770334628.png",
    dilution: "Diluant synthétique ou eau à 5% selon la formulation.",
    density: "1.08 ± 0.05 g/cm³",
    cov: "< 25 g/L (Haute protection résine)",
    outils: "Pinceau vernis à poils fins, rouleau laqueur.",
    preparation: "Ponçage fin du bois ou dépoussiérage méticuleux du support.",
    longDescription: "Traitement de protection extérieure totalement invisible et perlant protégeant des graisses et graffiti. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Menuiseries et boiseries", "Bardages extérieurs", "Finitions de prestige"]
  },

  // ==================== EXTÉRIEUR - SOLUTIONS ====================
  {
    id: "ext-antifissure",
    name: "ANTIFISSURE",
    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Hydro-Élastomère",
    description: "Peinture d'imperméabilisation élastomère haute élasticité, idéale pour ponter les fissures actives de façade.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Capacité de pontage jusqu'à 2.5mm", "Imperméabilité totale à l'eau liquide", "Excellente tenue aux amplitudes thermiques", "Fini mat garnissant"],
    image: "/prisma-color-website/images/AntiFissure.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Peinture d'imperméabilisation élastomère haute élasticité, idéale pour ponter les fissures actives de façade. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-enduit-carrelage",
    name: "ENDUIT CARRELAGE",
    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Adhésion Directe Sols",
    description: "Enduit-colle étanche spécial terrasse permettant d'unifier les sols extérieures recouverts de faïence avant peinture.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Super adhérence ciment-résine", "Résistant au gel-gél extérieur", "Étanchéité secondaire adjointe", "Application à la spatule large"],
    image: "/prisma-color-website/images/EnduitCarrelage.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Enduit-colle étanche spécial terrasse permettant d'unifier les sols extérieures recouverts de faïence avant peinture. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-antihumidite",
    name: "ANTIHUMIDITÉ",
    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Hydrofuge Coupe-Barrière",
    description: "Traitement minéralisant hydrofuge de profondeur destiné à assainir et étanchéifier les soubassements bruts.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["S'oppose aux remontées par capillarité", "Fort pouvoir durcisseur moléculaire", "Idéal contre les dalles poreuses", "Invisible ou recouvrable"],
    image: "/prisma-color-website/images/Antihumidité.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Traitement minéralisant hydrofuge de profondeur destiné à assainir et étanchéifier les soubassements bruts. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-prisma-flex",
    name: "PRISMA FLEX",
    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Étanchéité Liquide",
    description: "Résine élastique d'étanchéité liquide continue formant une membrane caoutchouteuse imperméable pour terrasses.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Allongement exceptionnel > 400%", "Résistance à la stagnation d'eau", "Terrasses non circulables et combles", "S'applique sans jointures"],
    image: "/prisma-color-website/images/PrismaFlex.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Résine élastique d'étanchéité liquide continue formant une membrane caoutchouteuse imperméable pour terrasses. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-prisma-fibre",
    name: "PRISMA FIBRE",
    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Mortier Armé Fibres",
    description: "Mortier de surfaçage technique armé de micro-fibres de verre synthétiques, empêchant la fissuration mécanique façades.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Résistance extrême à la traction", "Garnissage direct des éclats de béton", "Ponçage facile", "Excellent support d'accroche"],
    image: "/prisma-color-website/images/PrismaFibre.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Mortier de surfaçage technique armé de micro-fibres de verre synthétiques, empêchant la fissuration mécanique façades. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  },
  {
    id: "ext-izo-10",
    name: "IZO 10",
    category: "exterior",
    subCategory: "SOLUTIONS",
    line: "Gamme Solutions Facade",
    tag: "Réflecteur Thermique",
    description: "Peinture d'étanchéité et d'isolation thermo-réflective, bloquant le rayonnement solaire infrarouge pour isoler les toitures.",
    coverage: "4-7 m²/L par couche ou kg/m²",
    coverageMultiplier: 6,
    dryingTime: "Sec au toucher : 4h, Circulation : 24h",
    finishes: ["Mat technique", "Brillant structuré"],
    features: ["Abaisse doucement la température intérieure", "Membrane étanche élastique continue", "Haute réflectivité solaire certifiée", "Application simple et à haut rendement"],
    image: "/src/assets/images/paint_bucket_ext-izo-10.png",
    fallbackImage: "/src/assets/images/paint_bucket_facade_1780770349775.png",
    dilution: "Prêt à l'emploi ou dilution selon fiche spécifique.",
    density: "1.52 ± 0.05 g/cm³",
    cov: "< 35 g/L (Normes techniques d'étanchéité)",
    outils: "Rouleau polyuréthane, brosse dure, pistolet pneumatique.",
    preparation: "Éliminer l'humidité résiduelle, traiter la source d'infiltration avant peinture.",
    longDescription: "Peinture d'étanchéité et d'isolation thermo-réflective, bloquant le rayonnement solaire infrarouge pour isoler les toitures. Spécialement conçu pour satisfaire les normes de haute qualité au Maroc, ce produit offre un confort d'application inédit et une durabilité remarquable.",
    usage: ["Caves et parkings", "Terrasses d'étanchéité", "Zones humides et joints"]
  }
];

export const MOROCCAN_COLORS: Color[] = [
  { id: "prisma-green", name: "Vert Prisma", hex: "#6ca352", category: "nature", description: "Le vert officiel Prisma, symbole d'authenticité et de nature marocaine." },
  { id: "prisma-gold", name: "Or de Fès", hex: "#d2a632", category: "chaleureux", description: "Un jaune ocre riche et lumineux, inspiré par la finesse et la splendeur de l'artisanat de Fès." },
  { id: "prisma-red", name: "Rouge Marrakech", hex: "#dc1d24", category: "chaleureux", description: "Un rouge vibrant et terreux, capturant la chaleur des remparts de la ville ocre sous le soleil couchant." },
  { id: "ocean-safi", name: "Bleu de Safi", hex: "#1e5299", category: "mineral", description: "Un bleu azur profond et captivant qui évoque la célèbre faïence de Safi." },
  { id: "dune-sahara", name: "Sable du Sahara", hex: "#e7c08a", category: "chaleureux", description: "Un ton sable chaud, apaisant et très polyvalent pour les intérieurs modernes." },
  { id: "atlas-slate", name: "Ardoise de l'Atlas", hex: "#4a535a", category: "mineral", description: "Un gris foncé majestueux et texturé, tiré des rocheuses du Haut Atlas." },
  { id: "white-moulay", name: "Blanc Moulay Idriss", hex: "#fcfcfa", category: "neutre", description: "Un blanc pur avec une touche d'ivoire très douce, apportant de l'éclat aux pièces sombres." },
  { id: "terracotta-ouarzazate", name: "Terre de Kasbah", hex: "#c87d55", category: "chaleureux", description: "Un terracotta chaleureux qui rappelle l'enduit de terre crue des Kasbahs du Sud." },
  { id: "mint-valley", name: "Menthe de l'Ourika", hex: "#a4cbb4", category: "nature", description: "Un vert de menthe poivrée pastel, relaxant, idéal pour introduire de la fraîcheur." },
  { id: "charcoal-casbah", name: "Charbon de Mejjat", hex: "#1c1d1f", category: "neutre", description: "Le noir charbon de notre charte graphique. Profond, élégant et riche." },
  { id: "pearl-rabat", name: "Brume de Rabat", hex: "#e0e3e5", category: "neutre", description: "Un gris perle lumineux inspiré de la brume côtière matinale de la capitale." },
  { id: "copper-medina", name: "Cuivre de la Médina", hex: "#b46548", category: "chaleureux", description: "Une nuance cuivrée métallique polie, douce mais pleine de caractère." }
];

export const MOCK_ROOMS: Room[] = [
  {
    id: "salon",
    name: "Salon Contemporain",
    label: "Séjour & Espace à Vivre",
    viewBox: "0 0 800 450",
    elements: [
      { id: "bg", name: "Plancher & Arrière-plan", defaultColor: "#e5dec9", d: "M 0 0 L 800 0 L 800 450 L 0 450 Z" },
      { id: "floor", name: "Sol en Parquet", defaultColor: "#a38d72", d: "M 0 320 L 800 320 L 800 450 L 0 450 Z" },
      { id: "wall-left", name: "Mur d'Accent Gauche", defaultColor: "COLOR_PLACEHOLDER", d: "M 0 0 L 220 50 L 220 320 L 0 320 Z" },
      { id: "wall-back", name: "Mur Principal", defaultColor: "COLOR_PLACEHOLDER_BG", d: "M 220 50 L 580 50 L 580 320 L 220 320 Z" },
      { id: "wall-right", name: "Mur Droit", defaultColor: "#f3f3f0", d: "M 580 50 L 800 0 L 800 320 L 580 320 Z" },
      { id: "sofa", name: "Canapé Style Marocain", defaultColor: "#2a2d34", d: "M 280 220 L 520 220 C 530 220, 540 230, 540 240 L 540 290 L 260 290 L 260 240 C 260 230, 270 220, 280 220 Z M 220 250 L 260 250 L 260 300 L 220 300 Z M 540 250 L 580 250 L 580 300 L 540 300 Z" },
      { id: "pillow-1", name: "Coussin Or fès", defaultColor: "#d2a632", d: "M 290 235 C 290 225, 330 225, 330 235 L 330 270 L 290 270 Z" },
      { id: "pillow-2", name: "Coussin Vert", defaultColor: "#6ca352", d: "M 470 235 C 470 225, 510 225, 510 235 L 510 270 L 470 270 Z" },
      { id: "lamp", name: "Suspension Cuivre", defaultColor: "#b46548", d: "M 400 50 L 400 110 M 370 110 L 430 110 L 415 130 L 385 130 Z" },
      { id: "frame", name: "Tableau Déco", defaultColor: "#ffffff", d: "M 340 70 L 460 70 L 460 150 L 340 150 Z" },
      { id: "frame-inner", name: "Contenu Tableau", defaultColor: "#e5f0e0", d: "M 350 80 L 450 80 L 450 140 L 350 140 Z" }
    ]
  },
  {
    id: "facade",
    name: "Façade Extérieure",
    label: "Riad & Villa",
    viewBox: "0 0 800 450",
    elements: [
      { id: "sky", name: "Ciel Azur", defaultColor: "#abccee", d: "M 0 0 L 800 0 L 800 450 L 0 450 Z" },
      { id: "ground", name: "Sol Pavé", defaultColor: "#939ba2", d: "M 0 350 L 800 350 L 800 450 L 0 450 Z" },
      { id: "main-wall", name: "Corps de Façade", defaultColor: "COLOR_PLACEHOLDER", d: "M 80 80 L 720 80 L 720 350 L 80 350 Z" },
      { id: "roof", name: "Toiture Tuiles vertes", defaultColor: "#325732", d: "M 60 80 L 740 80 L 700 45 L 100 45 Z" },
      { id: "door-frame", name: "Encadrement Arche", defaultColor: "COLOR_PLACEHOLDER_ALT", d: "M 340 180 C 340 130, 460 130, 460 180 L 460 350 L 340 350 Z" },
      { id: "door", name: "Porte Sculptée", defaultColor: "#58200c", d: "M 355 190 C 355 155, 445 155, 445 190 L 445 350 L 355 350 Z" },
      { id: "window-l", name: "Fenêtre Gauche", defaultColor: "#eaeceb", d: "M 180 140 L 260 140 L 260 220 L 180 220 Z" },
      { id: "window-r", name: "Fenêtre Droite", defaultColor: "#eaeceb", d: "M 540 140 L 620 140 L 620 220 L 540 220 Z" },
      { id: "window-bar-l", name: "Grilles Gauche", defaultColor: "#111111", d: "M 180 180 L 260 180 M 220 140 L 220 220" },
      { id: "window-bar-r", name: "Grilles Droite", defaultColor: "#111111", d: "M 540 180 L 620 180 M 580 140 L 580 220" },
      { id: "plant-pot", name: "Vase Terracotta", defaultColor: "#b05427", d: "M 290 310 L 320 310 L 315 350 L 295 350 Z" },
      { id: "plant-green", name: "Plante Menthe", defaultColor: "#417441", d: "M 285 295 C 295 285, 315 285, 325 295 C 335 285, 320 270, 305 270 C 290 270, 275 285, 285 295 Z" }
    ]
  },
  {
    id: "chambre",
    name: "Chambre à Coucher",
    label: "Suite Parentale ou Enfant",
    viewBox: "0 0 800 450",
    elements: [
      { id: "bg", name: "Plafond", defaultColor: "#fafafa", d: "M 0 0 L 800 0 L 800 450 L 0 450 Z" },
      { id: "floor", name: "Sol Carrelage beige", defaultColor: "#eae3d2", d: "M 0 350 L 800 350 L 800 450 L 0 450 Z" },
      { id: "headboard-wall", name: "Tête de lit (Mur d'appui)", defaultColor: "COLOR_PLACEHOLDER", d: "M 120 40 L 680 40 L 680 350 L 120 350 Z" },
      { id: "wall-left", name: "Mur Gauche", defaultColor: "#eef2e6", d: "M 0 0 L 120 40 L 120 350 L 0 350 Z" },
      { id: "wall-right", name: "Mur Droit", defaultColor: "#fbf9f4", d: "M 680 40 L 800 0 L 800 350 L 680 350 Z" },
      { id: "bed", name: "Sommier Lit", defaultColor: "#b2abab", d: "M 230 260 L 570 260 L 570 350 L 230 350 Z" },
      { id: "headboard", name: "Tête de lit Cuir", defaultColor: "#6c4d37", d: "M 210 180 L 590 180 L 590 260 L 210 260 Z" },
      { id: "blanket", name: "Couverture de lit", defaultColor: "#4f6e5a", d: "M 240 280 L 560 280 L 560 350 L 240 350 Z" },
      { id: "pillows", name: "Oreillers", defaultColor: "#fcfcfa", d: "M 260 220 L 370 220 L 370 260 L 260 260 Z M 430 220 L 540 220 L 540 260 L 430 260 Z" },
      { id: "pillows-acc", name: "Coussinet Ocre", defaultColor: "#d2a632", d: "M 350 240 L 390 240 L 410 270 L 370 270 Z" },
      { id: "shelf", name: "Table de chevet bois", defaultColor: "#93633e", d: "M 140 290 L 190 290 L 190 350 L 140 350 Z M 610 290 L 660 290 L 660 350 L 610 350 Z" }
    ]
  }
];