name: Déploiement automatique GitHub Pages

on:
  push:
    branches: ["main"] # Se déclenche dès que tu push sur main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installer les dépendances
        run: npm install

      - name: Compiler le projet (Build)
        run: npm run build

      - name: Téléverser le dossier de production
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Dossier généré par Vite

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4